typed-ember/glint

- packages/environment-ember-loose/ember-modifier/index.ts
I'm not sure how to test this.
> Fix Ember Modifier class

- packages/environment-ember-loose/-private/intrinsics/get.d.ts
- packages/environment-ember-loose/__tests__/intrinsics/get.test.ts
> Fix `get` returning `unknown` for objects that can be `undefined`

- README.md
@dfreeman @wagenet Thanks for your comments! This should fix #158.
> Readme: Info on adding nested components to registry

- packages/environment-ember-loose/-private/intrinsics/component.d.ts
- packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
> The `{{component}}` helper silently accepts nullable values

- README.md
> Add helper and modifier docs

- packages/transform/__tests__/template-to-typescript.test.ts
- packages/transform/src/template-to-typescript.ts
> Handle spinal-case arg names

- packages/transform/__tests__/offset-mapping.test.ts
- packages/transform/src/template-to-typescript.ts
> Handle arg name position inference more carefully

- packages/core/src/cli/index.ts
- packages/core/src/cli/perform-check.ts
> Don't pretend the CLI can check individual files

- test-packages/ts-ember-app/app/components/foo.hbs
- test-packages/ts-ember-app/app/helpers/affix.ts
- test-packages/ts-ember-app/tests/integration/components/foo-test.ts
I've had this lying around for a while and keep meaning to commit it.
> Add class-based helper to ts-ember-app test package

- docs/known-limitations.md
I believe as of #307 we don't need this anymore!?
> Remove re-exports from known limitations

- docs/contents.md
- docs/diagnosing-common-error-messages.md
We can expand this over time; for now, just the first couple items I know of!
> Add docs for common error messages

- packages/environment-ember-loose/-private/environment/index.ts
> Fix name of environment-ember-loose main function

- packages/environment-ember-template-imports/-private/environment/index.ts
> Add `component` to template-imports environment built-ins

- packages/template/-private/keywords/in-element.d.ts
- packages/template/__tests__/keywords/in-element.test.ts
Resolves https://github.com/typed-ember/glint/issues/340
> in-element can take a ShadowRoot

- packages/environment-glimmerx/-private/dsl/globals.d.ts
- packages/environment-glimmerx/__tests__/globals.test.ts
- test-packages/js-glimmerx-app/src/App.js
- test-packages/ts-glimmerx-app/src/App.ts
- test-packages/ts-glimmerx-app/src/GreetingHeader.ts
- test-packages/ts-glimmerx-app/tests/rendering/App.test.js
- yarn.lock
We actually use this to create rehydratable regions of a page
> feat: expose component helper for glimmerx

- packages/core/__tests__/cli/incremental.test.ts
- packages/core/src/cli/perform-check.ts
@dfreeman encountered a scenario where the `.buildinfo` file was generated but empty. The first commit here is a first pass to verify that it does get generated at least sometimes. Unfortunately, it does not reproduce the bug; but it *does* tell us that this at least *generally* works.
> core/cli: fix empty `.buildinfo` files with `--incremental`

- docs/ember/template-only-components.md
> Note that generic template-only-component signatures are not supported

- packages/core/src/cli/options.ts
- test-packages/ts-ember-app/tsconfig.json
> Ensure we don't conflict with `declarationMap: true`

- packages/core/__tests__/transform/template-to-typescript.test.ts
- packages/core/src/transform/template/template-to-typescript.ts
> Honor lowercase in-scope variables when used as components

- docs/ember/routes-and-controllers.md
> Add documentation note about error substate routes

- packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
- packages/core/src/transform/diagnostics/augmentation.ts
- test-packages/test-utils/src/project.ts
> Use `{{get}}` notation in `noPropertyAccessFromIndexSignature` diagnostics

- docs/ember/installation.md
This was a setup configuration detail that would have saved me some time!
> Small note about ember-template-imports

- docs/ember/helper-and-modifier-signatures.md
> Fix "Helper and Modifier Signatures" code example

- .github/workflows/plan-release.yml
- .github/workflows/publish.yml
- .release-it.yml
- CHANGELOG.md
- RELEASE.md
- package.json
- packages/vscode/package.json
- pnpm-lock.yaml
- removes release-it
- central changelog (project-wide changelog)
- a changelog previous did not exist in this repo at all
Notes / docs: https://github.com/embroider-build/release-plan
> Setup release-plan for releases

- GLINT_V2.md
> Update GLINT_V2.md readme

- packages/core/src/transform/template/template-to-typescript.ts
> Fix glimmer/syntax deprecation

- packages/core/src/transform/template/rewrite-module.ts
- packages/core/src/volar/ember-language-plugin.ts
- packages/core/src/volar/gts-virtual-code.ts
- packages/tsserver-plugin/src/typescript-server-plugin.ts
- test-packages/package-test-core/__tests__/transform/rewrite.test.ts
> Fix auto-imports for first import

- packages/core/src/config/environment.ts
https://github.com/typed-ember/glint/pull/939#issuecomment-3338330763
cc @bwbuchanan
> Reinstate additionalSpecialForms

- packages/core/src/cli/run-volar-tsc.ts
> Allow V2 addons to get .d.ts declarations instead of .gts.d.ts
