README.md

Previously, the README said that it was possible to do this, but did not make clear *how* to do this.

Show using `glint` to replace `tsc --noEmit`

---

packages/template/-private/keywords/each.d.ts
packages/template/__tests__/keywords/each.test.ts

I can't seem to run tests locally (i.e. most of them fail) so let's see what the CI says.

Fix `each` not working with a `readonly` array

---

.vscode/launch.json

This adds a preLaunchTask to run `build` before launching the extension development host.

build before launch in Debug Extension

---

packages/core/src/common/transform-manager.ts
packages/core/src/language-server/index.ts
packages/transform/src/index.ts

I spent a bit of time profiling with Glint open in a non-toy-sized project and found a few pieces of low-hanging fruit for speeding things up:
1. **Keep Babel from doing unnecessary work**: `@babel/core`'s `parseSync` was doing a file system crawl looking for configuration files for every _single_ parse. Even assuming the OS was smart about caching those results, we were spending a lot of time in there. That behavior is now disabled (and is something we can consider doing once ourselves in the future if we have the need to support more exotic `.js` syntaxes).
2. **Cache negative transform results**: we now cache the result of transforming a file even if that result is "we didn't need to transform it", since just doing the analysis to see if we might need to check is more expensive than …

Performance improvements

---

packages/environment-ember-loose/-private/intrinsics/component.d.ts
packages/environment-ember-loose/-private/intrinsics/input.d.ts
packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
packages/environment-ember-loose/-private/intrinsics/textarea.d.ts
packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
packages/environment-ember-loose/__tests__/intrinsics/input.test.ts
packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
packages/environment-ember-loose/__tests__/intrinsics/textarea.test.ts
packages/template/-private/integration.d.ts

When we migrated to enforce correct usage of modifiers and `...attributes`, we didn't add `Element` declarations for the built-in `<Input>`, `<Textarea>` and `<LinkTo>` components. The `{{component}}` intrinsic also didn't pass through its target's `Element` information.
This PR takes care of both of those issues. Fixes #85

Type primary elements properly for built-in components

---

README.md
packages/environment-ember-loose/-private/index.ts
packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
packages/environment-ember-loose/ember-component/index.ts
packages/environment-ember-loose/glimmer-component/index.ts
packages/environment-ember-loose/package.json

Currently we don't have a way to express the kind of value `{{component}}` returns in userland. This PR introduces a `ComponentLike<T extends ComponentSignature>` type to `@glint/environment-ember-loose`.
`ComponentLike` is a unifying type for anything that can be invoked as a component. This includes subclasses of `EmberComponent` and `GlimmerComponent` (note: the classes themselves, _not_ their instances) as well as `{{component}}`'s return value. In this way it's now possible for users to write an appropriate type when they expect to receive or yield a component, using the same `ComponentSignature` basis as they already use for defining components themselves.
This PR also introduces a `ComponentWithBoundArgs<T extends ComponentLike, ArgNames>` type as a useful shorthand for …

Introduce `ComponentLike` and associated types

---

packages/environment-ember-loose/-private/dsl/globals.d.ts
packages/environment-ember-loose/-private/intrinsics/each.d.ts
packages/environment-ember-loose/-private/intrinsics/get.d.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
packages/environment-ember-loose/__tests__/intrinsics/get.test.ts
packages/environment-ember-loose/ember-component/helper.ts

This PR contains fixes for a handful of issues reported with `environment-ember-loose`:
- class-based helpers no longer have `undefined` stripped from their return type (fixes #87)
- `{{each}}` handles Ember arrays and native `Iterable` values (fixes #118)
- `{{get}}` handles `ObjectProxy` instances, which allows for template-native access of fields from things like ember-data's `AsyncBelongsTo`, even if it's not quite as ergonomic as just writing `{{proxy.field}}` (fixes #104)

Bugfix batch for `environment-ember-loose`

---

packages/core/__tests__/language-server/completions.test.ts
packages/core/__tests__/language-server/definitions.test.ts
packages/core/__tests__/language-server/hover.test.ts
packages/core/__tests__/language-server/references.test.ts
packages/core/__tests__/language-server/rename.test.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/util/index.ts

If we ever try to look up the translated TS code for a particular location and find ourselves still looking at a template, it means we didn't know what to do with that `.hbs` file and asking TypeScript about it will lead to a bad time. This change guards against that scenario.
This should fix #124.

Don't crash for operations on an unaffiliated template

---

packages/template/-private/dsl/invoke.d.ts
packages/template/__tests__/custom-invokable.test.ts
packages/template/__tests__/invoke-emit.test.ts

Putting an `Element` value in a mustache, or returning one from a helper, adds that node to the DOM in that location. Fixes #100

Allow emitting `Element` values

---

packages/core/src/cli/perform-check.ts

Here's a simple one that fixes #81. It turns out if we aren't emitting declaration files, we shouldn't print declaration diagnostics. Who would've thought? 🙂

Don't print declaration diagnostics when we aren't emitting declarations

---

packages/template/-private/dsl/resolve.d.ts
packages/template/__tests__/emit-component.test.ts
test-packages/ts-ember-app/app/components/foo.hbs
test-packages/ts-ember-app/app/components/wrapper-component.ts

It's legal to invoke a potentially-undefined component; if there's nothing there, the engine will just skip it entirely. Fixes #135.

Allow invoking nullable component values

---

packages/core/__tests__/language-server/diagnostics.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template-to-typescript.ts

In light of #143 there's likely to be some further changes in this area, but in the short term this will fix #142.

Ensure the invocation-context 𝛄 doesn't trigger an unused symbol warning

---

packages/template/-private/dsl/emit.d.ts
packages/template/-private/dsl/types.d.ts

The assorted `@glimmer` packages often end up causing transitive type errors for people if their versions don't quite line up or sometimes just if they're doing something TypeScript has more recently deemed an error condition.
As an example that recently came up [in Discord](https://discord.com/channels/480462759797063690/484421406659182603/829792501966700576):
```
node_modules/@glimmer/reference/dist/types/lib/validators.d.ts:79:52 - error TS2422: A class can only implement an object type or intersection of object types with statically known members.
79 export declare class MonomorphicTagImpl implements MonomorphicTag {
~~~~~~~~~~~~~~
node_modules/@glimmer/runtime/dist/types/lib/component/curried-component.d.ts:6:87 - error TS2677: A type predicate's type must be assignable to its …
```

Avoid a direct `@glimmer/runtime` reference

---

packages/core/__tests__/cli/check.test.ts
packages/core/__tests__/language-server/completions.test.ts
packages/core/__tests__/language-server/hover.test.ts
packages/environment-ember-loose/__tests__/component.test.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/environment-ember-loose/__tests__/intrinsics/action.test.ts
packages/environment-ember-loose/__tests__/intrinsics/component.test.ts
packages/environment-ember-loose/__tests__/intrinsics/each-in.test.ts
packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
packages/environment-ember-loose/__tests__/intrinsics/fn.test.ts
packages/environment-ember-loose/__tests__/intrinsics/input.test.ts
packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts
packages/environment-ember-loose/__tests__/intrinsics/textarea.test.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/environment-glimmerx/__tests__/helper.test.ts
packages/template/-private/dsl/emit.d.ts
packages/template/__tests__/attributes.test.ts
packages/template/__tests__/custom-invokable.test.ts
packages/template/__tests__/emit-component.test.ts
packages/template/__tests__/keywords/component.test.ts
packages/template/__tests__/keywords/each.test.ts
packages/template/__tests__/keywords/let.test.ts
packages/template/__tests__/keywords/with.test.ts
packages/template/__tests__/resolution.test.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template-to-typescript.ts

In #138, we reworked the way components and vanilla HTML elements were emitted. This had several nice effects, but it also exacerbated a problem that was already lurking.
As a general rule, TypeScript discards any narrowing information about a mutable variable or field inside a closure that captures it, because there's no way for it to guarantee that the narrowing still applies. Concretely:
```ts
function myFunction(input: { foo: string | number }) {
if (typeof input.foo === 'string') {
// `input.foo` is a string here
[1, 2, 3].forEach(() => {
// `input.foo` is back to `string | number` here
});
}
}
```
In the example above, even though we as humans can say it's unlikely that `input.foo` will change before that `forEach` callback is invoked, TypeScript has no way of knowing that. For all …

Ensure type narrowing propagates downward

---

packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/__tests__/component.test.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-ember-loose/ember-component/index.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-ember-loose/glimmer-component/index.ts

Prior to this change we were _only_ exporting the constructor signature for upstream classes. This change ensures we also reflect static members like `extend`.
Fixes #147.

Ensure we reexport static members from upstream classes

---

README.md
packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/__tests__/component-like.test.ts
packages/environment-ember-loose/__tests__/ember-component.test.ts
packages/environment-ember-loose/__tests__/glimmer-component.test.ts
packages/environment-ember-loose/ember-component/index.ts

While not super common, classic Ember components (as well as those that use custom component managers) can accept positional args when invoked with curlies. This PR adds `PositionalArgs` as a valid signature member for `EmberComponent` and `ComponentLike` in order to capture those cases.
Note: while the static property that's used to configure this at runtime on an Ember component is called `positionalParams`, I went with `PositionalArgs` for consistency with helper and modifier signatures (as well as `Args` itself on the component signature).
I also noticed in working on this that we had types tests for `EmberComponent`'s Glint integration, but not for `GlimmerComponent` or `ComponentLike`, so I added coverage for those as well.
Fixes #105

Introduce `PositionalArgs` for component signatures

---

packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-glimmerx/component/index.ts
packages/template/__tests__/resolution.test.ts
packages/template/__tests__/test-component.ts

Currently, people who have `class MyComponent extends Component<MyArgs>` and are adopting Glint are naturally inclined to change that to `Component<{ Args: MyArgs }>`. Unfortunately, if the `MyArgs` type is declared as an `interface`, that change will fail with a confusing error:
```
Type '{ Args: MyArgs; }' does not satisfy the constraint 'ComponentSignature'.
Types of property 'Args' are incompatible.
Type 'MyArgs' is not assignable to type 'Record<string, unknown>'.
Index signature is missing in type 'MyArgs'.(2344)
```
The underlying reason for this is that TS will infer an index signature for type aliases, but is unwilling to do so for interfaces because [that's more unsafe due to the potential for declaration merging](https://github.com/microsoft/TypeScript/issues/15300#issuecomment- …

Remove `Record`-based constraints on signature members

---

.github/workflows/ci.yml

When this repo was private, it made sense to wait for Linux to pass before even trying to test Windows. Now that Actions minutes aren't so tight, though, we're probably better off running the Windows job ASAP, as it takes about as long as Linux + TS Nightly _combined_.

Don't block Windows on Linux in CI

---

packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/src/language-server/glint-language-server.ts

Don't crash when requesting diagnostics on an excluded template.

---

packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts

> A link will be active if current-when is true or the current route is the route this link would transition to.
https://api.emberjs.com/ember/release/classes/Ember.Templates.components/methods/LinkTo?anchor=LinkTo

Allow LinkTo current-when to be boolean

---

packages/environment-ember-loose/__tests__/ember-component.test.ts
packages/environment-ember-loose/__tests__/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/environment-ember-loose/__tests__/modifier.test.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-ember-loose/ember-component/index.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-ember-loose/glimmer-component/index.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/environment-glimmerx/component/index.ts

For situations like writing types tests, since there's no (public) way to verify how an entity will behave when invoked in a template, it's reasonable to want to be able extract a class's signature type from the instance type. However, because of the `Get<T, 'PositionalArgs' []>`-style lookups we do to handle the presence or absence of keys in a signature, TypeScript can't `infer` backwards through those conditional types to reconstruct the original signature.
This PR captures the signature type directly on the instance type for all the signature-having classes we export. Notably, this type has _no_ bearing on how these entities behave in templates, and is only to enable recovery of the original signature.
An alternative to this approach would be to encourage the use of `Invokable`, …

Capture given signatures so TS can infer them from the concrete type

---

packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
packages/environment-ember-loose/__tests__/intrinsics/link-to.test.ts

Support named args with `{{link-to}}`

---

packages/environment-ember-loose/-private/intrinsics/each.d.ts
packages/environment-ember-loose/__tests__/intrinsics/each.test.ts

If `{{each}}` is given an `any` value (or a non-iterable value), the type of the value it yields comes out as `unknown`. This can cause a cascade of type errors that aren't actually helpful because the root issue is the value you tried to iterate over.
In TS itself:
```ts
for (let value of ([] as any)) {
value; // any
}
for (let value of 123) { // type error on `123`
value; // any
}
```
This change causes `{{each}}` to behave the same way.

Ensure `{{each}}` yields `any` given `any` or a non-iterable value

---

README.md
packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
packages/environment-ember-loose/-private/intrinsics/each.d.ts
packages/environment-ember-loose/__tests__/component-like.test.ts
packages/environment-ember-loose/__tests__/ember-component.test.ts
packages/environment-ember-loose/__tests__/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/intrinsics/each-in.test.ts
packages/environment-ember-loose/__tests__/intrinsics/each.test.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/template/-private/keywords/each.d.ts
packages/template/-private/keywords/with.d.ts
packages/template/__tests__/custom-invokable.test.ts
packages/template/__tests__/keywords/with.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template-to-typescript.ts

Requires `Yields` to use `else`, but still allows for `{{yields to="inverse"}}`

Prefer `else` over `inverse`

---

.github/workflows/ci.yml

The decompression step for `actions/cache` on Windows is [known to be slow](https://github.com/actions/cache/issues/442), and in our case it's significantly slower than just installing dependencies from scratch.
In representative sample runs, we spent:
|Step|Linux | Windows | Windows without `actions/cache` |
|-|-|-|-|
| Restore Cache | 0:07 | 3:03 | 0:00 |
| Install Dependencies | 0:22 | 0:40 | 2:18 |
| Save Cache | 0:06 | 0:11 | 0:00 |
| **Total** | **0:37** | **3:36** | **2:18** |

Skip `actions/cache` for Windows CI

---

README.md

This points folks toward https://github.com/Gavant/glint-template-types where the community has begun collecting Glint-compatible types for popular addons 😄

Link to `glint-template-types` repo in the README

---

packages/template/-private/dsl/emit.d.ts
packages/template/-private/integration.d.ts
packages/template/__tests__/emit-component.test.ts

Similar in spirit to #173, this PR ensures that trying to invoke an invalid component doesn't produce a cascade of errors that mask the true problem.
As an example of this, prior to this PR if I were to typo the name of a component in my template, in addition to the "that's not a valid key of `Globals`" error, I'd see a couple of others relating to trying to pass a default block to an unknown component.
This change ensures we produce `any` where appropriate in those situations so that we avoid a cascade and don't bury the real error.

Avoid cascading errors on invalid component invocations

---

README.md
packages/core/__tests__/cli/declaration.test.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/environment-glimmerx/component/index.ts
packages/template/-private/dsl/emit.d.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/inlining/index.ts
packages/transform/src/inlining/tagged-strings.ts
packages/transform/src/template-to-typescript.ts
test-packages/ts-glimmerx-app/src/App.ts

In GlimmerX, a standalone template is a valid component:
```js
const Foo = hbs`
Hello, {{@target}}!
`;
export default hbs`
<Foo @target="World" />
<Foo @target="Everyone" />
`;
```
This PR enables these template components to work in Glint, using a type annotation to associate a signature where needed:
```ts
interface FooSignature {
Args: { target: string };
}
const Foo: TemplateComponent<FooSignature> = hbs`
Hello, {{@target}}!
`;
export default hbs`
<Foo @target="World" />
<Foo @target="Everyone" />
`;
```
Just as with class-based components, template components that don't declare a signature are assumed to accept no args, have no splattributes element, and never yield.
This PR tweaks the emit from `@glint/transform` slightly in order for type inference to work for the template …

Support standalone templates as components in GlimmerX

---

README.md
packages/config/__tests__/environment.test.ts
packages/config/src/environment.ts
packages/config/src/index.ts
packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
packages/environment-ember-loose/-private/environment/index.ts
packages/environment-ember-loose/-private/index.ts
packages/environment-glimmerx/-private/environment/index.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/src/inlining/tagged-strings.ts
packages/vscode/__fixtures__/ember-app/tests/integration/component-test.ts
packages/vscode/__tests__/smoketest-ember.test.ts
test-packages/ts-ember-app/tests/integration/components/bar-test.ts
test-packages/ts-ember-app/tests/integration/components/ember-component-test.ts
test-packages/ts-ember-app/tests/integration/components/qux-test.ts

This PR makes Glint work with `hbs`-tagged template strings used in rendering tests. 
```ts
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';
test('MyComponent works', async function (assert) {
// If `@arg` is declared to be a string, you'll get a squiggle here
await render(hbs`<MyComponent @arg={{123}} />`);
assert.dom().hasText('...');
});
```
In some TypeScript codebases it's common practice to define per-module (or even per-test) context types that include additional properties. In these cases, it's possible to include the context type as a parameter to `render`:
```ts
import { render } from '@ember/test-helpers';
import { hbs } from 'ember-cli-htmlbars';
import type { TestContext } from 'ember-test-helpers';
interface MyContext extends …
```

Support Ember rendering tests

---

.github/workflows/ci.yml
packages/config/src/environment.ts
packages/core/__tests__/language-server/completions.test.ts
packages/core/src/cli/options.ts
packages/environment-ember-loose/-private/intrinsics/input.d.ts
packages/environment-ember-loose/-private/intrinsics/textarea.d.ts
packages/environment-ember-loose/__tests__/helper.test.ts
packages/template/-private/keywords/in-element.d.ts
packages/template/__tests__/tsconfig.json
packages/transform/src/index.ts
packages/transform/src/inlining/index.ts
packages/transform/src/map-template-contents.ts
packages/transform/src/template-to-typescript.ts

The new [`--strictOptionalProperties` flag](https://github.com/microsoft/TypeScript/pull/43947) landed in `typescript@next` in the past couple days, and it's enabled by default under the `--strict` umbrella.
We have a few violations of this in Glint itself which are fixed in this PR. Unfortunately, this also causes trouble in some upstream declarations as well—the two that were immediately obvious were `@glimmer/runtime` and `vscode-languageserver-protocol`.
For now we're setting `strictOptionalProperties: false` to keep things passing, but as the feature matures and makes it into a stable TypeScript release, we may want to see about getting those fixed up so we can turn the flag back on and avoid potentially accidentally breaking our own consumers.

Get TS nightly green

---

.github/workflows/ci.yml
packages/config/src/environment.ts
packages/core/src/common/load-typescript.ts
packages/core/src/language-server/binding.ts
packages/transform/src/map-template-contents.ts

There's been some churn lately in `typescript@next` around what gets included under `strict: true`.
- `useUnknownInCatchVariables` is in
- `exactOptionalPropertyTypes` (née `strictOptionalProperties`) is out
This has resulted in some churn for us in the "watch for breaking changes coming down the pipe" stesp in CI, but this PR should get us green again.

Get TS nightly passing (once more, with feeling)

---

package.json
packages/config/src/config.ts
packages/core/__tests__/cli/declaration.test.ts
packages/core/src/common/transform-manager.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-loose/__tests__/type-tests/integration-declarations.test.ts
packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-glimmerx/helper/index.ts
packages/environment-glimmerx/modifier/index.ts
packages/template/__tests__/emit-component.test.ts
packages/template/__tests__/resolution.test.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/inlining/companion-file.ts
packages/transform/src/template-to-typescript.ts
packages/transform/src/transformed-module.ts
test-packages/ts-ember-app/app/routes/classic-route.ts
test-packages/ts-ember-app/package.json
test-packages/ts-ember-app/tsconfig.json
tsconfig.compileroptions.json
yarn.lock

This upgrades the Glint codebase to `typescript@4.3` and ensures we play nicely with `noImplicitOverride` and `noPropertyAccessFromIndexSignature`.
For `noImplicitOverride`, we could run afoul when defining a template on a subclass of some other component that already had an associated template. Since we can't know during emit whether or not to use `override`, for now we include the class name as part of the template key to avoid collisions. Though it's not included in the TS 4.4 Beta blog post, [class static blocks](https://github.com/tc39/proposal-class-static-block) look to be [landing as part of that release](https://github.com/microsoft/TypeScript/pull/43370), at which point we can make use of those for template definitions and the need for a field name goes away entirely.
For …

Upgrade to TS 4.3 and play nicely with new flags

---

packages/config/src/config.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/__tests__/utils/project.ts
packages/core/src/common/document-cache.ts
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/index.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/src/index.ts
packages/transform/src/inlining/companion-file.ts

In most scenarios, a template inherits the "typedness" of the script it's attached to. If the backing module is TS, anything Glint sees as illegal usage in the template will get a red squiggle. If it's JS, we'll never give any squiggles, only provide go-to-definition, hover info, etc.
With template-only components, though, we have no way of knowing whether the author intends for the template to be typechecked or not. Currently we always treat standalone templates as targets for typechecking, but that's of course undesirable in JS-only projects.
This PR adds a `checkStandaloneTemplates` flag that users can specify in `.glintrc` to specify whether standalone templates should be typechecked or not.
This option should likely be documented as part of the larger "how to use Glint in JS …

Add `checkStandaloneTemplates` configuration option

---

packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
packages/environment-ember-loose/ember-component/template-only.ts
packages/template/-private/dsl/types.d.ts

Currently the `{{component}}` keyword will give a type error when used with a `templateOnlyComponent()`, as the latter is declared as a `DirectInvokable`, which is generally reserved for special constructs like `{{#each}}` and `{{#let}}`.
This makes template-only components regular invokables, allowing `{{component}}` to work with them.

Ensure `{{component}}` works with template-only components

---

.github/workflows/ci.yml
packages/vscode/__tests__/support/launch-from-cli.js

As of VSCode 1.62.0, something [deep in the internals of the built-in `vscode.typescript-language-features` extension](https://github.com/microsoft/vscode/blob/6ae9e9d86cb9facd5f041c6c8c2dfc629b84017d/extensions/typescript-language-features/src/typescriptServiceClient.ts#L1066) triggers an unhandled promise rejection upon opening a `.ts` file. The line in question is nothing new, but my guess (based on the version this started in) is that it's likely some change to either the extension or text document lifecycle introduced during recent work to make VSCode run more happily in the browser.
Regardless of the reason, the unhandled `undefined` rejection ultimately bubbles up through Jest as a test failure during whatever test happens to be running when it happens, leading to a whole cascade …

Fix extension smoke test failures

---

packages/core/__tests__/language-server/completions.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/vscode/__tests__/smoketest-ember.test.ts

We ask a lot already of the Actions runners in CI when we launch full VS Code instances to run our extension smoke tests, but recently it seems file system notifications have been a bit flaky there.
There's no reason those tests _really_ need to be part of that suite, though, since 99% of what they're testing is logic in the language server itself that we can trigger by testing against an in-memory instance and explicitly sending a "hey this file changed" notification. While this means we're no longer testing that that hook is wired up in the VSC extension correctly, I think that small loss in coverage is outweighed by keeping the test suite stable and avoiding "testing the framework" with the extension system's file watching infrastructure.
I also tweaked a completions test to avoid …

Move file add/delete tests into the LS suite

---

packages/config/__tests__/environment.test.ts
packages/config/__tests__/load-config.test.ts
packages/config/src/config.ts
packages/config/src/environment.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/src/inlining/companion-file.ts

This change allows for users to specify multiple `environment` values in their Glint config.
This is the first step toward being able to create an `ember-template-imports` Glint environment. Currently, even a "totally `template-imports`" project will still have loose-mode templates for things like routes, so projects would typically want to make use of both the `template-imports` environment _and_ `@glint/environment-ember-loose` in the same project.
A few notes:
- only one active environment can determine how standalone `.hbs` files are handled
- only one active environment can determine how a particular imported template tag behaves
If either of those rules is violated, an error is raised when Glint boots up and loads the configuration.
Subsequent work will enable environments to …

Support multiple active environments in a project

---

packages/environment-ember-loose/-private/intrinsics/fn.d.ts

... because sometimes you have functions with more arguments. :)

Add overloads to `fn` with more arguments

---

packages/environment-glimmerx/-private/dsl/index.d.ts
packages/environment-glimmerx/__tests__/resolve.test.ts
packages/template/-private/dsl/resolve.d.ts
packages/template/-private/dsl/types.d.ts

In beginning to play around with an `glint-environment-ember-template-imports` package, I got exasperated with the tedium and error-prone-ness of having to define types for both `resolve` and `resolveOrReturn`.
On reflection, we should be able to trivially define the latter in terms of the former, so this PR introduces a utility type to `@glint/template` to enable just that and lessen the burden on environment maintainers.

Add `ResolveOrReturn` utility type to `@glint/template`

---

.github/workflows/ci.yml
packages/core/bin/glint-language-server.js
packages/core/bin/glint.js
packages/core/src/cli/index.ts
packages/transform/src/inlining/index.ts
yarn.lock

A few separate but related issues have popped up as our upstream dependencies (specifically the Babel-related ones) have evolved lately:
- Browserslist gets cranky when it's not on a recent enough version. We don't actually care because we aren't doing transpilation for real targets, but Babel ends up implicitly loading it on startup, which can trigger the warning. Accordingly, we disable the warning in the entrypoint to the language server and CLI executables.
- [babel/babel#14113](https://github.com/babel/babel/pull/14113) made `generate(someTSTypeParameterDeclarationNode)` throw, as it now cares about details of its parent node. Babel should maybe handle that more gracefully, but it's trivial for us to work around by generating code for the declarations individually rather than …

Deal with dependency drift issues

---

packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/src/inlining/tagged-strings.ts
packages/transform/src/mapping-tree.ts

Fixes #224.
Today I learned that, according to [the ECMAScript spec](https://tc39.es/ecma262/#sec-static-semantics-trv), when the sequence `\r\n` (not the escapes, but the actual characters they represent) appears in the contents of a template string, they're normalized to be treated the same as a single `\n`.
> The TRV of _LineTerminatorSequence_ :: &lt;CR> &lt;LF> is the String value consisting of the code unit 0x000A (LINE FEED).
Babel honors this, causing template strings parsed from files using Windows line endings to be "missing" their `\r`s in the value their AST node contains. This, in turn, meant we were getting off-by-`n` errors in inline templates, where `n` was the number of lines into the template we were looking at any given time.
To avoid this problem, when we deal with …

Handle Windows line endings correctly in inline templates

---

.eslintrc
README.md
packages/environment-ember-loose/-private/index.ts
packages/environment-glimmerx/-private/dsl/integration-declarations.d.ts
packages/environment-glimmerx/-private/index.ts
packages/environment-glimmerx/package.json
test-packages/ts-ember-app/package.json
test-packages/ts-ember-app/types/demo-ember-app/index.d.ts
test-packages/ts-glimmerx-app/package.json
test-packages/ts-glimmerx-app/types/index.d.ts

While vanilla TypeScript tooling will always have an incomplete picture of what's happening in a project with Glimmer templates (otherwise there'd be no use for Glint!), many users keep that tooling active. This may be for access to richer features (see #130) or because they're working in an environment without full support for Glint.
Glint environments augment the types of certain packages, and then Glint itself implicitly adds references to those augmented types when transforming source code. Because TypeScript by itself won't add those references, code relying on the augmentations won't typecheck under vanilla `tsc` or `tsserver`.
To work around this, folks have added imports themselves to pull in the necessary module augmentations from private paths, which isn't ideal for them as …

Make it easier to avoid errors with vanilla `tsc`

---

packages/core/src/common/transform-manager.ts
packages/core/src/language-server/binding.ts
packages/environment-ember-loose/-private/dsl/globals.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/component.test.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/src/index.ts
packages/transform/src/util.ts

This is the result of chasing down a handful of bugs in the issue tracker that seemed like they'd be easy to squash. It includes fixes for:
- #216 
- #211
It also adds a warning to files when something goes wrong when we try to emit diagnostics. This won't necessarily catch a case where we should be emitting diagnostics but aren't because we think everything is fine, but it _will_ flag the situation to the user if an exception is being thrown and we know for a fact something is wrong, which we believe may be the case in #215.

A small bug bash 🐛 

---

packages/config/__tests__/environment.test.ts
packages/config/src/config.ts
packages/config/src/environment.ts
packages/core/__tests__/language-server/completions.test.ts
packages/environment-ember-loose/-private/environment/index.ts
packages/environment-glimmerx/-private/environment/index.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/inlining/tagged-strings.ts
packages/transform/src/scope-stack.ts
packages/transform/src/template-to-typescript.ts

This change overhauls the way environments declare how their exported tags handle assumptions about scope capture and template globals.
Today, we track the set of statically-known identifiers in scope as we traverse a template, potentially seeding that scope with the available set of JS identifiers depending on whether the environment's tag config declares `capturesOuterScope: true`. We then assume anything that _doesn't_ appear in that scope must be global.
Today's approach largely works, but by default it means autocomplete doesn't work for non-global identifiers, since upon seeing `{{fo}}` we'd emit `Globals['fo']` even if `foo` is an in-scope block param. We've baked in some heuristic workarounds for this, but they lead to issues like #182.
Additionally, this approach requires us to …

Overhaul global scope management

---

packages/core/src/common/transform-manager.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/package.json
packages/transform/src/index.ts
packages/transform/src/inlining/companion-file.ts
packages/transform/src/inlining/index.ts
packages/transform/src/inlining/tagged-strings.ts
packages/transform/src/util.ts
yarn.lock

Today we use Babel to parse files we expect to need to perform transformation on. This brings some niceties, like a sensible AST design and built-in scope analysis that allows us to ask questions like "does identifier _X_ refer to export _Y_ from module _Z_?".
However, it also comes with costs. Version drift in Babel has produced issues like #244, and even with the work in #95 to minimize extra work the parser does, Babel's `parseSync` is roughly 7-8x slower than TypeScript's `createSourceFile`.
<details>
<summary>The quick, totally unscientific comparison</summary>
Comparing 5000 runs of:
```js
babel.parseSync(source, {
filename: 'test.ts',
babelrc: false,
configFile: false,
code: false,
presets: ['@babel/preset-typescript']
});
```
To:
```js
ts.createSourceFile(
source,
'test.ts', …
```

Use TS for script parsing rather than Babel

---

packages/core/__tests__/cli/custom-extensions.test.ts
packages/core/__tests__/language-server/custom-extensions.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/__tests__/utils/project.ts
packages/core/src/cli/perform-check.ts
packages/core/src/cli/perform-watch.ts
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/binding.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/index.ts
packages/core/src/language-server/util/index.ts

Working on custom syntax support in extra file extensions has revealed a few places where we haven't been handling the state of the filesystem quite correctly. Some are new and unique to custom extensions, while others have been lurking for some time.
The core of the matter came down to two things:
- not providing custom implementations of `fileExists` and `watchDirectory`
- being sloppy about tracking changes to `rootFiles` (which is how TS decides what to typecheck) over time in the language server
For the former, those two methods were added to `TransformManager` and plugged in appropriately to the CLI and language server.
For the latter, `GlintLanguageServer` now manages two sets of known documents: those that exist on disk and those that exist in the editor. It keeps these lists up …

Handle FS events more robustly

---

packages/config/__tests__/environment.test.ts
packages/config/src/environment.ts
packages/config/src/index.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/src/index.ts
packages/transform/src/inlining/tagged-strings.ts
packages/transform/src/template-to-typescript.ts
packages/vscode/__fixtures__/custom-app/src/Greeting.custom
packages/vscode/__fixtures__/custom-app/src/index.custom
packages/vscode/__tests__/smoketest-custom.test.ts
test-packages/glint-environment-custom-test/env.js
test-packages/ts-custom-app/src/Greeting.custom
test-packages/ts-custom-app/src/index.custom

#251 introduced support for environments to opt custom file extensions into analysis by Glint, but required that they use syntax that Glint could already understand. For something like [the proposed `.gjs`/`.gts` format](https://github.com/emberjs/rfcs/pull/779) to work, environments need the ability to transform any custom syntax into a format that Glint can parse and operate on.
This PR provides that ability to environments as a two-phase operation. The first, `preprocess`, is a string-to-string mapping that allows for converting exotic syntax into something that the TypeScript parser can recognize. Environments can also pass any additional data they collect as part of this process on to be used in the next phase.
The second phase, `transform`, operates on a parsed `ts.SourceFile` AST. …

Support preprocessing for custom extensions

---

packages/environment-ember-loose/ember-component/helper.ts
yarn.lock

This patches `packages/environment-ember-loose/ember-component/helper.ts` to have it's version of `Helper` include the same `Opaque` that `@ember/component/helper` extends, allowing it to continue to work with `@types/ember__component@4.0.6`.

Fix Helper types compat

---

packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-ember-loose/package.json
packages/template/package.json
test-packages/ts-ember-app/package.json
yarn.lock

This PR ensures Glint is compatible with the recent signature-aware releases of `@glimmer/component`, `ember-modifier`, and `@types/ember__component`. ~It's intended to be the last release in the `0.7.x` line.~
The only actual bugfix is a change to our reexports for `ember-modifier`. Prior to this PR, `tsc` (for whatever reason) was inlining `(...args: ConstructorParameters<typeof Modifier>)` to `(owner: unknown, args: import("ember-modifier").ModifierArgs<unknown>)`, which breaks with `ember-modifier@3`, where `ModifierArgs` doesn't take any type parameters.
Pulling `ModifierConstructor` into its own type prevents this behavior, for reasons I don't 100% understand. Normally that would concern me, but this _should_ be the penultimate release of Glint which includes these reexports, and …

Ensure compatibility with latest upstream Ember/Glimmer types

---

packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-ember-loose/ember-component/index.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-ember-loose/glimmer-component/index.ts

This is the same fix as the one for `ember-modifier` in #275 applied to the constructors for `EmberComponent`, `Helper` and `GlimmerComponent`.

Prevent `tsc` from inlining implementation details from upstream

---

packages/environment-ember-loose/glimmer-component/index.ts

This makes types less safe, but previously, TypeScript would squash
the type param making it incorrect.

Fix issue where Component super args were incorrect

---

README.md

It took me a bit to figure out the best way to extend the Registry type from a .d.ts file for both components and helpers, so I figured this may be helpful in the readme.

Update readme with example of third-party types

---

packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
packages/template/-private/index.d.ts
packages/template/__tests__/component-like.test.ts
packages/template/__tests__/helper-like.test.ts
packages/template/__tests__/modifier-like.test.ts
packages/template/package.json
test-packages/ts-ember-app/app/components/bar/index.ts
test-packages/ts-ember-app/app/components/ember-component.ts
test-packages/ts-ember-app/app/components/foo.ts
test-packages/ts-ember-app/app/components/qux.ts
test-packages/ts-ember-app/app/components/template-only-module.ts
test-packages/ts-ember-app/app/components/test-cases/subclassing/parent.ts
test-packages/ts-ember-app/app/components/wrapper-component.ts
test-packages/ts-ember-app/app/helpers/repeat.ts
test-packages/ts-ember-app/app/pods/components/baz/component.ts
test-packages/ts-ember-app/types/demo-ember-app/index.d.ts
test-packages/ts-ember-app/types/ember-welcome-page/index.d.ts

One of the pending items from #283 is providing projects using native imports and signatures with a way to describe the type of yielded components, as `@glint/environment-ember-loose`'s `ComponentLike` currently does. This is a vital piece for describing the signature of components that do things like:
```hbs
{{yield (hash
Input=(component "our-special-input" thing=this.defaultThingValue}}
)}}
```
Now that signature formats have been more or less standardized across the board, we can expose standardized `ComponentLike`, `HelperLike` and `ModifierLike` types from `@glint/template` itself rather than homing them in an environment-specific location. Subclasses of `Component`, `Helper` and `Modifier` are respectively assignable to their corresponding `*Like` types, as are the return values …

Expose `@glint/template` utility types

---

.gitbook.yaml
docs/contents.md
docs/ember/component-signatures.md
docs/ember/contextual-components.md
docs/ember/imports.md
docs/ember/installation.md
docs/ember/rendering-tests.md
docs/ember/routes-and-controllers.md
docs/ember/template-only-components.md
docs/ember/template-registry.md
docs/ember/typing-your-dependencies.md
docs/getting-started.md
docs/glimmerx/component-signatures.md
docs/glimmerx/imports.md
docs/glimmerx/installation.md
docs/glimmerx/template-components.md
docs/known-limitations.md
docs/overview.md

With the work in #283 and #285 landing soon, we need a place to put a migration guide for moving from the old environment-specific reexports and legacy signature formats to using native imports and the finalized signature format from https://github.com/emberjs/rfcs/pull/748.
The README is already massive, so it clearly doesn't make sense to incorporate yet another thing there. We could just make a `MIGRATING.md` and call it a day, but this seemed like a good opportunity to break apart the existing docs into separate pages to publish on [GitBook](https://www.gitbook.com/) the same way we do for `ember-cli-typescript`.
There's plenty of cleanup and improvements we could make to these docs, but the goal of this initial pass is just to take the existing content and structure it slightly more …

Break out README contents into GitBook docs

---

docs/contents.md
docs/migrating.md

This adds a guide for users to migrate from the `environment-ember-loose` reexports to the native import paths.
Note that this does not touch the baseline documentation everywhere else, which still uses the reexports. I'll update that (along with the remaining unmigrated tests) as part of 0.8.0.

Add a migration guide for native imports

---

packages/environment-ember-loose/-private/utilities.ts
packages/environment-ember-loose/ember-component/helper.ts
packages/environment-ember-loose/ember-component/index.ts
packages/environment-ember-loose/ember-modifier/index.ts
packages/environment-ember-loose/glimmer-component/index.ts
packages/vscode/__fixtures__/ember-app/app/app.ts
packages/vscode/__fixtures__/ember-app/app/components/classic-layout.ts
packages/vscode/__fixtures__/ember-app/app/components/colocated-layout.ts
packages/vscode/__fixtures__/ember-app/app/components/pod-layout/component.ts

This marks all of the exported types and values from `@glint/environment-ember-loose` as deprecated with pointers to alternatives.

Deprecate `environment-ember-loose` reexports

---

packages/config/package.json
packages/config/src/index.ts
packages/config/tsconfig.json
packages/config/types/silent-error.d.ts

Throwing a regular error gave an IMO confusing error message, with the full stack trace etc.

Use `SilentError` when no config is found

---

packages/core/src/cli/index.ts
packages/transform/src/index.ts

This adds a new flag to the `glint` CLI command that causes it to write out the internal intermediate representation of each file, after it has been transformed into the form that TypeScript itself will "see".
Given an app containing:
```js
//  app/components/example.gts
import Component from '@glimmer/component';
export class A extends Component {
<template>Hello</template>
}
```
Run `glint --debug-intermediate-representation`, and your project dir will also contain:
```js
// GLINT_DEBUG/app/components/example.gts
import Component from '@glimmer/component';
export class A extends Component {
static { ({} as typeof import("glint-environment-ember-template-imports/-private/dsl")).template(function(𝚪: import("glint-environment-ember-template-imports/-private/dsl").ResolveContext<A>, χ: …
```

Enable dumping of the intermediate representation source code

---

packages/config/src/environment.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/src/inlining/tagged-strings.ts

This is a fix for #297.
It allows environment-defined transforms to emit template locations via meta instead of using `node.pos` (which is unreliable when the source has been preprocessed into an intermediate form).

Fix preprocessed template locations

---

package.json
yarn.lock

This upgrades the glint monorepo's typescript version.
The reason I want to do this is because I'm preparing to move glint-environment-ember-template-imports into here, and that package relies on typescript's support for class static blocks that is not available in the present version.

TypeScript upgrade

---

.github/workflows/ci.yml
package.json
test-packages/js-glimmerx-app/package.json
test-packages/ts-ember-app/package.json

Since we are planning on cutting a 'major' with v0.8.0 shortly anyway, seems like a good time to upate the Node versions we are targeting. Among other things, this lets us take advantage of package `exports`, at least once we can require TS 4.7 (which we should be able to do in a 0.9 release in May).

Update to use Node 14+

---

test-packages/glint-environment-custom-test/package.json
test-packages/js-glimmerx-app/package.json
test-packages/ts-custom-app/package.json
test-packages/ts-ember-app/package.json
test-packages/ts-glimmerx-app/package.json

This makes working directly in test packages nicer when your default node version is < 14.

Extend volta config in test packages

---

packages/environment-glimmerx/package.json

As alluded to in #307, we're going to hold off on publishing any `0.8.x` versions of `@glint/environment-glimmerx` until GlimmerX is in a place to work with Glint with native imports, pending
- https://github.com/glimmerjs/glimmer-experimental/pull/147
- https://github.com/glimmerjs/glimmer-experimental/pull/148
By marking the package `private` for the time being, it will be skipped as we publish v0.8 releases of the other `@glint` packages.

Mark `environment-glimmerx` temporarily private to avoid publishing

---

packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template-to-typescript.ts
test-packages/ts-ember-app/app/components/nocheck-me.hbs

This adds a `@glint-nocheck` directive, similar to [`@ts-nocheck` in .ts files](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-7.html#-ts-nocheck-in-typescript-files), that will cause Glint to not report errors for the whole template (while still providing autocompletion, types, and other diagnostics). It is basically a global `@git-ignore`. While `include` already provides a way to only check specified templates, workflows like [lint-to-the-future](https://github.com/mansona/lint-to-the-future) use file-based ignores. This provides a quick way to opt-out individual templates from type-checking that is easily discoverable by readers of the template.

Add @glint-nocheck directive.

---

docs/known-limitations.md

Fixes a broken link in the docs by adjusting it's relative path.
The resulting link changes from
https://github.com/typed-ember/glint/blob/main/docs/packages/vscode
to 
https://github.com/typed-ember/glint/tree/main/packages/vscode

docs: Fix broken link to VS Code extension

---

packages/template/-private/index.d.ts
packages/template/-private/integration.d.ts
test-packages/ts-ember-app/tests/integration/types/empty-signature-test.ts

Currently, if a developer explicitly writes `Args: {}` in their signature, that bypasses the `EmptyObject` shenanigans we do to ensure that [excess property checking](https://levelup.gitconnected.com/typescript-excess-property-checks-6ffe5584f450) is enabled when invoking a component (or helper, modifier, etc), because those only kick in when the `Args` key isn't specified at all.
This change adds a guard at the 'last mile' of signature expansion in `@glint/template` to explicitly detect `{}` (and other similar key-less types like `object`) and sub in `EmptyObject` instead.
This handles explicit `{}` usage from end users, and it also allows (but doesn't force) us to stop doing the `EmptyObject` dance in `@glimmer/component`, `ember-modifier` and `@types/ember__component` if we choose.

Handle explicit `Args: {}` and similar

---

docs/ember/component-signatures.md

This updates the Ember component signature example in the docs to keep the args defined within the signature (like we teach for Glimmer components), and pull them out into a type alias that can be extended (`interface Greeting extends GreetingSignature['Args']` is not allowed, unfortunately). The motivation is that this form facilitates easier migration to Glimmer components because the signature is already in the form we want for Glimmer. Users would simply delete the `GreetingArgs` type alias and the `interface Greeting extends GreetingArgs {}` lines rather than needing to modify the signature by moving the arguments inside. I also think that the consistency between the Glimmer and Ember signatures is a win.

For Ember components, keep args in signature, use type alias

---

docs/ember/authoring-addons.md

This has come up recently so I thought it would be good to add a section on how to do it properly.

Add section for adding types to non-TS addons

---

docs/ember/authoring-addons.md

- Add preceding `/` to all file paths for clarity/consistency
- Change reference to `/addon/glint.d.ts` to `/addon/glint.ts` for consistency

Minor docs fixes for Glint types for non ts addons section

---

packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts

- Currently, template-only components do not work with `WithBoundArgs` because they are not `ComponentLike`. Introduce a failing test to demonstrate the problem (and prevent future regressions).
- Passing `args: never` instead of having an abstract constructor involved tripped up the assignability relation for `ComponentLike` with `TemplateOnlyComponent`: `new (arg: never) => Type` is not assignable to `new (...args: any) => Type` ([example][1]). Instead, introduce an abstract constructor type which the `TemplateOnlyComponent` interface can *extend*, using interface merging with the existing base definition in Ember itself (currently on DefinitelyTyped) to provide the desired semantics and constraints:
- The type acts like a class for our purposes, meaning we can use it to get instance …

Make Ember template-only components ComponentLike

---

packages/core/src/common/scheduling.ts

I think this area of the language server is going to get reworked a bit more broadly as we rethink the relationship between Glint and TS config locations and look toward better support for Glint projects set in arbitrary places in a workspace. For now, though, this fixes a silly (but terrible) but where we aren't actually canceling pending work like we mean to be when a change comes in.
Fixes #265

Don't flood the language server work queue when many changes come in

---

packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/src/language-server/glint-language-server.ts

We had an issue (#263) _only_ for diagnostics and _only_ for the language server where leading trivia (comments and whitespace) at the start of a file would cause offsets to be incorrect.

Account for leading trivia in source files for LSP diagnostic locations

---

packages/core/src/cli/options.ts
packages/core/src/language-server/glint-language-server.ts
packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-loose/package.json
packages/environment-ember-template-imports/package.json
packages/environment-glimmerx/__tests__/helper.test.ts
packages/vscode/package.json

This PR fixes up a couple of issues that have popped up recently:
- The `ember-template-imports` environment is missing a declared dependency on `@glint/template`
- The CLI emits `declaration`-related diagnostics even when `--declaration` isn't passed if `declaration: true` is set in your `tsconfig.json`
- The language server doesn't resolve links the same way the `glint` CLI and `tsserver` both do, which can lead to different behavior in projects with `pnpm`'s linking shenanigans

[bugfix] Cleanup for dependency issues and CLI/LSP consistency

---

docs/diagnosing-common-error-messages.md

Closes https://github.com/typed-ember/glint/issues/362.

Fix import typo in doc

---

package.json
packages/core/package.json
packages/core/src/language-server/binding.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/messages.ts
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/package.json
packages/vscode/src/extension.ts
yarn.lock

This PR contains a handful of quality-of-life improvements for the language server and Code extension.
I've declared two new configuration options for the extension:
- `glint.trace.server`: The `vscode-languageserver` library already automatically honored this option to determine the level of logging it does for LSP messages, but now it shows up in the UI instead of requiring users to manually enter it in their preferences JSON file.
- `glint.debug`: Enables additional debugging commands in the editor (see below)
I've also added two new commands:
- `Glint: Restart Glint Server`: Manually restarts any active language server process(es), which is much quicker than restarting the entire Code extension host (and consistent with how TS itself and others work)
- `Glint: Show IR for Debugging`: …

Language server and Code extension improvements

---

docs/ember/installation.md
packages/config/__tests__/environment.test.ts
packages/config/src/environment.ts
packages/environment-ember-loose/-private/dsl/index.d.ts
packages/environment-ember-loose/-private/dsl/without-function-resolution.d.ts
packages/environment-ember-loose/-private/environment/index.ts
packages/environment-ember-loose/README.md
packages/environment-ember-loose/__tests__/environment.test.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-template-imports/-private/environment/index.ts
packages/environment-glimmerx/-private/environment/index.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template/inlining/companion-file.ts
packages/transform/src/template/inlining/tagged-strings.ts
packages/transform/src/template/template-to-typescript.ts
test-packages/ts-ember-app/app/components/ember-component.hbs
test-packages/ts-ember-app/app/components/ember-component.ts

This PR adds support for the default helper manager RFC to projects using `@glint/environment-ember-loose`. This support is enabled by default, but since the implementation only just landed and it may be some time before projects (particularly addons) are comfortable adopting it, we also allow opting out via a flag in the environment config.
Fixes #363

Support the default helper manager RFC in `environment-ember-loose`

---

packages/core/__tests__/cli/build.test.ts
packages/core/src/cli/index.ts

Building on top of the work in https://github.com/typed-ember/glint/pull/377, add correct handling for the `--force` flag. This simply passes it through directly to TypeScript itself.
(Draft because it builds on #381)

core/cli: implement `glint --build --force`

---

packages/core/__tests__/cli/build.test.ts
packages/core/src/cli/index.ts

Building on top of the work in #377, add correct handling for the `--clean` flag. This simply passes it through directly to TypeScript itself, and since we don't need to do anything else for a `--clean` invocation, this Just Works™. 🎉

core/cli: implement `glint --build --clean`

---

packages/core/__tests__/cli/declaration.test.ts
packages/core/__tests__/utils/project.ts

The latest TS 4.9 nightly build stopped including `declare` in emitted `type` declarations. We don't actually care about this, but it happened to break one of our snapshots.

Handle TS nightly changes to declaration emit

---

packages/config/__tests__/environment.test.ts
packages/config/__tests__/load-config.test.ts
packages/config/__tests__/loader.test.ts
packages/config/package.json
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/utils/project.ts
packages/core/package.json
packages/core/src/cli/index.ts
packages/core/src/cli/perform-build.ts
packages/core/src/cli/utils/sys-for-compiler-host.ts
packages/core/src/cli/utils/transform-manager-pool.ts
packages/core/src/common/transform-manager.ts
packages/environment-ember-loose/package.json
packages/environment-ember-template-imports/package.json
packages/scripts/package.json
packages/transform/package.json
yarn.lock

This should also include the bits required to support `--incremental` builds, since if TS *knows* that a build needs to be re-run and can report it in `--dry`, it can also *do* the build with `--incremental`.

core/cli: implement `glint --build --dry`

---

packages/core/__tests__/cli/incremental.test.ts
packages/core/src/cli/index.ts
packages/core/src/cli/options.ts

Include the flag in the CLI and incorporate it for both `--build` and regular builds.
The test here is intentionally minimal: we exercise a much broader set of features via the `--build` and especially `--build --dry` tests, which exercise these capabilities explicitly. Here, we just check that `--incremental` does the right thing when *not* in a `--build` context.

core/cli: add `glint --incremental` support

---

README.md
docs/ember/installation.md
docs/overview.md

I believe it's Ember 4, but if it's not I can change it, just so long as it's mentioned somewhere.
_edit: Ember 3.24+ seems more correct, and i verified this with my own testing_

Mention minimum Ember version

---

packages/core/__tests__/cli/declaration.test.ts
packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/route-and-controller.test.ts
packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
packages/environment-ember-template-imports/-private/dsl/index.d.ts
packages/environment-glimmerx/-private/dsl/index.d.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/template/-private/dsl/emit.d.ts
packages/template/-private/dsl/types.d.ts
packages/template/__tests__/attributes.test.ts
packages/template/__tests__/emit-component.test.ts
packages/template/__tests__/resolution.test.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/offset-mapping.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/__tests__/template-to-typescript.test.ts
packages/transform/src/template/inlining/companion-file.ts
packages/transform/src/template/inlining/index.ts
packages/transform/src/template/inlining/tagged-strings.ts
packages/transform/src/template/template-to-typescript.ts
packages/vscode/__tests__/helpers/async.ts
test-packages/ts-glimmerx-app/src/App.ts
test-packages/ts-template-imports-app/src/Playground.gts

Historically we've used a single `template()` function to act as the wrapper around our translated template bodies, deciding based on context whether to explicitly apply a type annotation to its `𝚪` context parameter or allow its type to be inferred.
This has generally worked for us, but it's resulted in:
- some additional complexity during transformation to propagate type parameters and their constraints from the backing class down to the function body representing the template
- needing to maintain a `ResolveContext` type for internal (i.e. template backing context) resolution that works completely differently from how external (i.e. invocation signature) resolution works via `resolve()`
- special casing templates with a backing class to always emit `as unknown` (or the JSDoc …

Break `template()` in two

---

packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/util/protocol.ts

This fixes #379, as well as fixing a longstanding issue where we (inexplicably) rewrite "unused symbol" diagnostics to be warnings instead of passing them through with the severity dictated by TS itself.

Avoid trying to load a local TypeScript instance from the LSP

---

packages/environment-glimmerx/README.md
packages/environment-glimmerx/package.json

In #308 we marked the `@glint/environment-glimmerx` package private to avoid publishing new versions until GlimmerX itself was in a state to support native integration. Now that the upstream changes have landed and we've made corresponding adjustments here in #384, we can start publishing that package again.

Start publishing `@glint/environment-glimmerx` again

---

docs/ember/installation.md
docs/glimmerx/installation.md
packages/core/package.json
packages/environment-glimmerx/package.json

We generally say "make sure you're on the latest version of X" in Discord and elsewhere when folks ask, and for some of those things we have `peerDependencies` declared, but we're missing some peerDeps and we never explicitly say in the documentation anywhere what our minimum supported versions are.

Explicitly document our expected peer versions

---

packages/environment-glimmerx/-private/dsl/globals.d.ts
packages/environment-glimmerx/-private/index.ts
packages/environment-glimmerx/.gitignore
packages/environment-glimmerx/globals/index.d.ts
test-packages/ts-glimmerx-app/package.json
test-packages/ts-glimmerx-app/src/App.ts
test-packages/ts-glimmerx-app/tsconfig.json
test-packages/ts-glimmerx-app/types/index.d.ts
test-packages/ts-glimmerx-app/webpack.config.js
yarn.lock

While GlimmerX is a module-centric world, applications can still have
macros that are defined by the surrounding build system. This was
partially there with `config.additionalGlobals` but we actually
need to expose a registry that can be merged into so that the
globals aren't `any` types

feat: Expose Globals registry to glimmerx

---

docs/contents.md
docs/directives.md

I took the liberty of building on the excellent work in #315 by @jamescdavis and applied the PR suggestions from @chriskrycho and @dfreeman. Having these missing from the docs deprives new users of an important adoption tool.

Document @glint directives, incorporating suggestions

---

packages/core/src/language-server/pool.ts

i have added support for glint in intellij, but it internally expects severity to be always set.

add severity to diagnostic error message

---

docs/contents.md
docs/glint-language-server.md

Git history clearly disagrees with me, but I feel like this is the third time I've deleted this page only to discover that it's still there. It's a remnant from when the docs were organized differently, and this remaining scrap of content about the language server isn't particularly useful to anyone.

Remove unhelpful `glint-language-server` docs page

---

yarn.lock

This _should_ fix the type errors we're getting with `typescript@next` in CI

Refresh `@types/node` for TS nightly fixes

---

package.json

This does not change our CI setup, which continues to use Node 14, and will do so until it leaves LTS. However, since Node 16 was the first version with support for Apple Silicon, this makes ESBuild (and thus our test setup) actually work "out of the box" on M1/M2-based Macs.
The errors provided without this are *utterly* inscrutable, such that I have wasted an hour or two dealing with it over the last months: I forget that it needs to be updated, and VS Code’s error lens does not surface enough information in its default view to make it obvious what the problem is, and when rerunning `yarn` it gets lost in the midst of many other informational messages, and then finally after 20 minutes I remember. This should solve that problem once and for all.

Use Node 16 for development

---

docs/contents.md
docs/with-js.md

This integrates the work done by @erinsinger93 in #208 into the updated docs site we landed later, and adds some extra content.
Closes #208

Add docs for JS usage, including an example

---

ARCHITECTURE.md

This will help folks navigate the overall structure of the doc. We can expand on it over time as makes sense. This first commit is necessarily incomplete, as it does not have all invariants or a visualization; we will add that while landing this.
[rendered](https://github.com/typed-ember/glint/blob/architecture-md/ARCHITECTURE.md)
<details><summary>Overall Glint flow diagram</summary>
<p align='center'>
</p>
</details>
<details><summary>Overall Glint flow diagram</summary>
<p align='center'>
</p>
</details>

Introduce an ARCHITECTURE.md file

---

ARCHITECTURE.md
docs/with-js.md

I had no idea we were enforcing this. Do we *want* to be? A discussion for a future point *after* CI is green again.
---
I, an idiot, merged PRs with this red earlier b/c I thought "Ah, these are just `.md` files, can't be actually the cause of CI being red, will check that later." 🙃

Fix CI: Prettier on .md files

---

.prettierignore

The formatting Prettier uses by default *does. not. match.* the formatting applied by GitBook. Having both present is a recipe for ongoing CI problems. (cf. 02e539fa)

chore: ignore Markdown files in Prettier

---

docs/diagnosing-common-error-messages.md

This adds notes for a couple of things that folks have asked about recently in Discord.

Add Common Error notes for `resolve` failures and missing `Globals` members

---

packages/config/src/environment.ts
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/utils/project.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/pool.ts
packages/environment-ember-template-imports/-private/environment/transform.ts
packages/environment-ember-template-imports/__tests__/transformation.test.ts
packages/transform/__tests__/debug.test.ts
packages/transform/__tests__/rewrite.test.ts
packages/transform/src/template/inlining/tagged-strings.ts
packages/transform/src/template/map-template-contents.ts
packages/transform/src/template/mapping-tree.ts
packages/transform/src/template/template-to-typescript.ts

Today when we capture embedded template content, we have a blurry notion of where the syntax that denotes the embedding, like the `hbs` tag and backticks or `<template>` wrapper, actually falls. From a mapping perspective, we treat it as effectively part of the template, and we generate extra whitespace around the template body before parsing it to account for the space that that embedding syntax takes up in the overall source.
This generally works fine, but it means that we never actually keep track of the real original contents of the template, only the whitespace-padded version. That makes it difficult to automate operations like adding `{{! @glint-nocheck }}` that, to be effective, want to understand things like the indentation of a template body.
As we look to the future where …

Capture embedding syntax and actual template content separately

---

packages/core/__tests__/cli/incremental.test.ts
packages/core/src/cli/options.ts

If the `incremental` key is present in the options we pass to TypeScript when performing a check, that takes precedence over what's in the project's `tsconfig.json`, even if it's `undefined`.
This ensures we only set that key if the `--incremental` flag was passed, otherwise falling back to whatever's in the project config.

Honor `incremental: true` in `tsconfig.json`

---

packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
test-packages/ts-ember-app/package.json
test-packages/ts-ember-app/tests/integration/components/render-test.ts

TS improved inference behaviors in a variety of ways in 4.8, one of which caught a discrepancy in our types. In 4.8+, using `render()` without a type parameter causes a super obtuse type error.
This change fixes the type inconsistency, and adds an explicit set of tests to capture our expected behavior for various usage in templates in `render` calls, both with and without an explicit `this` type.
Thanks to the inference improvements in 4.8, we no longer infer `never` for the `this` type in test templates when it's unspecified, meaning folks may (correctly) see some new red squiggles under `{{this.foo}}` when they upgrade. Anyone who wants to preserve the existing "don't bother checking what's on `this`" behavior can use `render<any>(...)` to make that explicit.
Normally we'd catch changes …

Fix `render` inference in TS 4.8+

---

packages/transform/__tests__/rewrite.test.ts
packages/transform/src/template/inlining/companion-file.ts

Previously, there were some cases where `as` could be used in a generated .js file. TS isn't happy about this.

Fix JS-backed types

---

packages/environment-ember-loose/-private/dsl/globals.d.ts
packages/environment-ember-loose/-private/intrinsics/unique-id.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/unique-id.test.ts
test-packages/ts-ember-app/app/components/ember-component.hbs

We'll still need to expose an import for `environment-ember-template-imports` once the actual runtime implementation is landed in Ember itself (and the base type is in DT and the preview types for us to stick a signature on), but for now this makes `{{unique-id}}` available as a global in loose mode.
Fixes #378

Add `{{unique-id}}` to `environment-ember-loose`

---

packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/transform/src/diagnostics/augmentation.ts

This PR updates some of our custom diagnostic augmentations:
- taking care of a false-positive detection for no-arg `{{yield}}` (fixes #375)
- suggesting a missing registry entry for a failed global lookup (fixes #398)
- clarifying the message when the first arg to `{{component}}` is bad (fixes #373)
- explicitly calling out that directly invoking a component via the `{{component}}` helper isn't possible with Glint and suggesting a workaround (also captured in #373)

Improve custom diagnostic messages

---

packages/scripts/package.json

Fixes #434.
Also a good motivator for us to move to pnpm here, since that will force us to be more careful about these things.

Add missing `glob` dependency to `@glint/scripts`

---

packages/core/__tests__/language-server/hover.test.ts
packages/core/package.json
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/glint-language-server.ts
test-packages/ts-ember-app/app/components/js-component.hbs
test-packages/ts-ember-app/app/components/js-component.js
yarn.lock

Currently if you open a file we _might_ be able to provide diagnostics for but in fact isn't something the language server is aware of, you can get an error like this:
```
Glint encountered an error computing diagnostics for this file. This is likely a bug in Glint; please file an issue, including any code and/or steps to follow to reproduce the error.
Error: Could not find source file: 'app/components/my-component.js'.
```
This might happen if you open a `.js` file with `allowJs: false`, or a `.gts` file in a project without the template-imports environment. Depending on the order files are opened in, it can also happen if we accidentally synthesize a `.ts` backing file for a `.hbs` one that actually has a `.js` module somewhere.
This change ensures we're a bit more careful in those …

Handle out-of-scope files more cleanly in the language server

---

packages/core/__tests__/language-server/completions.test.ts
packages/core/src/language-server/binding.ts
packages/core/src/language-server/glint-language-server.ts

As with #393, this still doesn't solve our underlying "only syntactically-valid templates can produce completions" problem, but it _does_ resolve the main issue called out in #436.
At a high level, several different related issues were coming together to produce the behavior described in #436:
- completions triggered as the result of typing a partial identifier are always considered `CompletionTriggerKind.Invoked` (this is per the LSP, not just a weird choice on Code's part)
- we weren't forwarding TS's sorting information through the LSP, so items didn't necessarily display in order of relevance
- standalone templates with a syntax error end up mapping to a 0-length span at the top level of the corresponding backing module, meaning that when we tried to produce completions for e.g. …

Further autocomplete improvements

---

docs/ember/authoring-addons.md
docs/ember/using-addons.md

Based on the discussion in #439, we want to advise addon authors to export a registry type from `<addon-name>/template-registry` rather than relying on declaration merging in `<addon-name>/glint`. This updates the documentation originally written by @simonihmig accordingly.
Closes #446

Update addon docs with the outcome of #439

---

package.json
yarn.lock

Thanks to the vagaries of Yarn's hoisting decisions, `@types/babel__traverse` suddenly stopped being installed in a location where it's visible to `babel-import-util`, causing our "Floating Dependencies" test job to start failing.

Refresh lockfile and ensure `@types/babel__traverse` is hoisted

---

packages/core/__tests__/transform/template-to-typescript.test.ts
packages/core/src/transform/template/template-to-typescript.ts

Avoid generating illegal TypeScript by emitting block param names such as `switch`, `default`, `var`, and so on.
Fixes #444.

Rename block param identifiers that conflict with JS/TS keywords.

---

packages/environment-ember-loose/-private/index.ts
packages/environment-ember-template-imports/-private/index.ts
packages/environment-glimmerx/-private/index.ts

This avoids compile error when building with --isolatedModules, which affects projects that directly link the sources for glint instead of importing it from npm.
There is no change to the compiled output.
Fixes #455

Add an export statement to */-private/index.ts

---

README.md
docs/ember/installation.md
docs/getting-started.md
docs/glimmerx/installation.md
docs/with-js.md
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
packages/environment-ember-loose/-private/intrinsics/get.d.ts
packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
packages/environment-ember-loose/package.json
packages/environment-ember-template-imports/package.json
packages/environment-glimmerx/-private/dsl/index.d.ts
packages/environment-glimmerx/-private/dsl/integration-declarations.d.ts
packages/environment-glimmerx/package.json
packages/template/-private/index.d.ts
packages/template/-private/integration.d.ts
packages/template/-private/signature.d.ts
packages/template/__tests__/signature-test.test.ts
packages/template/package.json
packages/vscode/README.md

This change addresses some long-standing issues with the dependency declarations in some of our packages:
1. Our environments should be declaring peerDeps on _every_ package they attempt to augment in order to ensure the target package is actually visible
2. Environments currently declare a direct dependency on `@glint/template`, which means they can end up getting their own copy, but `@glint/template` really needs to be a highlander package because all consumers need to be on the same page about the symbols it uses for branding
3. `@glint/template` forces a dependency on `@glimmer/component` for its `ExpandSignature` utility type, even though consumers of `@glint/template` may not need or want `@glimmer/component` themselves
For (1), this primarily means we add a bunch of optional …

Clean up package dependencies

---

packages/core/__tests__/cli/build-watch.test.ts
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/cli/incremental.test.ts
packages/core/__tests__/transform/debug.test.ts
packages/core/__tests__/transform/rewrite.test.ts
packages/core/src/cli/utils/patch-program.ts
packages/core/src/cli/utils/transform-manager-pool.ts
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/transform/template/map-template-contents.ts
packages/core/src/transform/template/template-to-typescript.ts
packages/environment-ember-template-imports/-private/dsl/integration-declarations.d.ts
packages/environment-ember-template-imports/-private/environment/index.ts
packages/environment-ember-template-imports/-private/environment/transform.ts
test-packages/test-utils/src/composite-project.ts

Aligning with the discussion in https://github.com/ember-template-imports/ember-template-imports/pull/18, this PR drops support for the `hbs` string tag from `ember-template-imports`. The expectation is that `ember-template-imports` itself is going to deprecate `hbs` soon, and since we have a good opportunity to make breaking changes at the moment, the `@glint/environment-ember-template-imports` package now _only_ operates on `<template>` literals.

Drop `hbs` tag support in `ember-template-imports`

---

packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
packages/environment-ember-loose/-private/intrinsics/component.d.ts
packages/environment-ember-loose/__tests__/type-tests/ember-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/glimmer-component.test.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/mut.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/outlet.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/unbound.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/unique-id.test.ts
packages/environment-ember-loose/__tests__/type-tests/route-and-controller.test.ts
packages/environment-ember-loose/__tests__/type-tests/template-only.test.ts
packages/environment-ember-template-imports/-private/dsl/index.d.ts
packages/environment-glimmerx/-private/dsl/index.d.ts
packages/environment-glimmerx/__tests__/component.test.ts
packages/environment-glimmerx/__tests__/helper.test.ts
packages/template/-private/dsl/emit.d.ts
packages/template/-private/integration.d.ts
packages/template/-private/signature.d.ts
packages/template/__tests__/component-like.test.ts
packages/template/__tests__/helper-like.test.ts
packages/template/__tests__/modifier-like.test.ts
packages/template/__tests__/signature-test.test.ts
packages/template/__tests__/test-component.ts
test-packages/ts-ember-app/tests/integration/types/empty-signature-test.ts

Now that we've [overhauled `[Invoke]`](https://github.com/typed-ember/glint/pull/447) to have a simpler internal representation, we're better positioned to ensure that various `ComponentLike` values property reflects the real-world subtyping relationship between their types.
As a concrete example, a value with the bare `ComponentLike` type represents a component that can be invoked with no args, no blocks, and no modifiers. Given a definition like this:
```ts
class MyComponent extends Component<{
Args: { name?: string };
Element: HTMLImageElement;
Blocks: { default: [] };
}> {}
```
The value `MyComponent` should be assignable to `ComponentLike`, because it _is_ legal to invoke without passing any args, blocks or modifiers.
If, however, the `name` arg were _not_ optional, then …

Validate assignability rules for `ComponentLike` and friends

---

.vscode/launch.json
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/messages.ts
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/__tests__/smoketest-template-imports.test.ts
packages/vscode/src/extension.ts

We don't document this command anywhere public and make no guarantees about its functionality (or even continued existence), but since we're bundling up breaking changes anyway, I'm taking this opportunity to tweak the message format we use for asking the language service about the transformed contents of a file. This allows the command to work in `.gts` files, and if you run it in a `.hbs` file, you'll now be taken to the backing module instead.

Support the `ShowIR` command for non-`.ts` files

---

docs/migrating.md
package.json
yarn.lock

I'll plan to link to this page from the `1.0.0-beta.1` release note. We can update with any further changes as needed during the beta cycle, and then I'll drop the beta disclaimer when we release `1.0.0` stable!

Add migration notes for 0.9 => 1.0

---

test-packages/ts-ember-preview-types/.eslintrc.js
test-packages/ts-ember-preview-types/app/components/bar/index.ts
test-packages/ts-ember-preview-types/app/components/ember-component.ts
test-packages/ts-ember-preview-types/app/components/foo.ts
test-packages/ts-ember-preview-types/app/components/qux.ts
test-packages/ts-ember-preview-types/app/components/test-cases/subclassing/parent.ts
test-packages/ts-ember-preview-types/app/components/wrapper-component.ts
test-packages/ts-ember-preview-types/app/pods/components/baz/component.ts

The `ts-ember-preview-types` test package intentionally tests classic, non-tagless components, so we should just disable the ESLint rules that complain about them "globally" for the whole package.

Disable anti-classic ESLint rules for `ts-ember-preview-types` test package

---

docs/ember/template-registry.md

This example is confusing (and incorrect) because the registry augmentation is not within the registry ambient module.

docs: move registry interface inside registry ambient module

---

docs/ember/installation.md
docs/glimmerx/installation.md
docs/migrating.md
package.json
packages/core/package.json
packages/scripts/package.json
yarn.lock

TypeScript deprecated certain signatures of their AST builder API based on changes they made to their node structure in anticipation of ES decorators (see https://github.com/typed-ember/glint/commit/ce5a668fd134f84a4bd6e23999cac7f100e7d577). The non-deprecated signatures are only available starting in TS 4.8, and it turns out we weren't testing against 4.7 despite claiming to support it.
This updates our docs to reflect the new minimum version and also makes the constraint explicit in our root `package.json`.

Update minimum supported TS version to 4.8

---

packages/core/src/cli/index.ts

This fixes a couple oddities relating to our conversion to ESM in the CLI, namely that `--version` and `--debug-intermediate-representation` were broken.
The former is fixed by reading our own `package.json` and manually specifying the version for `yargs`. The latter is incidentally also fixed by that, as we were using `require` to pull in a few additional modules for setting up the IR emit, and that isn't defined by default in a `type: 'module'` file in Node.

Fix up a couple ESM oddities in the CLI

---

packages/environment-ember-loose/-private/intrinsics/link-to.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/link-to.test.ts

This one is pretty much just what it says on the tin. Fixes #480.

Ensure `link-to` can still be invoked with only named args

---

docs/known-limitations.md
packages/vscode/README.md
packages/vscode/package.json
packages/vscode/src/extension.ts

This change adds a config option to the Code extension to customize the location from which we try to resolve `@glint/core`. This means that if, for example, your frontend and backend live in a single repository, you can open Code in the root of that repo and still tell Code where to load Glint from.

Add an option to the Code extension for where to look for @glint/core

---

packages/core/__tests__/cli/build.test.ts

I originally intended these to cover some scenarios which got covered in the regular `--build` tests, and never deleted them, and somehow we all missed them in code review, too. 🤷🏻‍♂️

Remove unused `--build` suite tests

---

packages/core/__tests__/cli/build.test.ts
packages/core/src/cli/perform-build-watch.ts
packages/core/src/cli/perform-build.ts
packages/core/src/cli/perform-watch.ts
packages/core/src/cli/utils/patch-program.ts
test-packages/test-utils/src/composite-project.ts

Because TypeScript's `--build` mode is primarily driven off of `emit()` calls to the underlying `Program` instances that make up the project, it's not always guaranteed to pull its diagnostics via the outer `BuilderProgram` diagnostic methods that we override in `patchProgram`.
If we silence diagnostics in those methods and TS subsequently sees the untransformed version of those diagnostics later, it will print those diagnostics for the user. Also troublingly, the presence of those diagnostics in combination with `noEmitOnError` will cause corresponding `.d.ts` files _not_ to be emitted for files that are suppressing template type errors with `@glint-nocheck`.
This change ensures that when we patch the outer program's diagnostic methods, we also patch the _inner_ program's corresponding …

Ensure we handle `@glint-nocheck` in composite projects correctly

---

packages/type-test/package.json

Without this, we'd include our tests and `tsconfig.json` when we  publish `@glint/type-test`, and npm would default to assuming we want this scoped package to be private and then 💥.

Update publish configuration for `@glint/type-test`

---

packages/core/__tests__/transform/template-to-typescript.test.ts
packages/core/src/config/types.cts
packages/core/src/transform/template/template-to-typescript.ts

Resolves #221. With this PR merged, you should be able to fully make use of type narrowing for discriminated unions.
Note that the type effects of these operators do not strictly match the semantics specified by RFC 562, in that they express **JavaScript truthiness** instead of **Handlebars truthiness**. It's not clear to me that it is possible to express Handlebars truthiness in TypeScript in such a way that you can usefully narrow types with it in combination with logical operators.
As these helpers have not yet been merged into Ember, you can opt in by adding to your glint config:
```json
{
"glint": {
"environment": {
"ember-loose": {
"additionalSpecialForms": {
"globals": {
"and": "&&",
"or": "||",
"not": "!"
}
}
},
"ember-template-imports": {
"additionalSpecialForms": {
"imports": { …
```

Add support for logical operators (RFC 562)

---

packages/core/__tests__/language-server/custom-extensions.test.ts
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/src/language-server/binding.ts
packages/core/src/language-server/config-manager.ts
packages/core/src/language-server/glint-language-server.ts
packages/core/src/language-server/index.ts
packages/core/src/transform/template/transformed-module.ts
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/__tests__/smoketest-js-glimmerx.test.ts
packages/vscode/__tests__/smoketest-template-imports.test.ts
packages/vscode/src/extension.ts

In practice Glint is language server that translates Ember templates and concepts into TypeScript code that then is typechecked using the off shelf TypeScript typechecker. If there are errors during the checking, text offsets of those errors are translated back into the original text offsets (in Ember templates and concepts) so that the developer can resolve the type errors.
This PR starts to plumb through more capabilities for the Glint language server, specifically we're starting with CodeActions. [CodeActions Requests](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#textDocument_codeAction) are sent from the client to server to get for fixes for problems in code including type fixes. Since Glint utilizes the underlying TypeScript …

Introduce CodeActions

---

packages/environment-ember-loose/-private/dsl/integration-declarations.d.ts
packages/environment-ember-loose/__tests__/type-tests/modifier.test.ts
packages/environment-ember-loose/package.json
test-packages/ts-ember-app/package.json
yarn.lock

with https://github.com/ember-modifier/ember-modifier/releases/tag/v4.0.0, we can't bump `ember-modifier` to v4.0.0 in the project due to `peerDependencies` range including only v3

Widen supported range for ember-modifier to include v4

---

packages/core/package.json
packages/core/src/cli/index.ts
packages/core/src/common/typescript-compatibility.ts
packages/core/src/language-server/pool.ts
yarn.lock

This PR expands on #504 (thanks, @NullVoxPopuli!) to enforce that we don't try to run with an older version of TS than we support. It covers both `--build` and non-`--build` invocations of the `glint` CLI, as well as the language server on a per-project basis.
Closes #504

Validate that TS meets our minimum supported version requirement

---

packages/core/src/language-server/binding.ts
packages/core/src/language-server/glint-language-server.ts

This requires #499
In this PR we thread through the `ConfigManager` through the vscode binding so that completions can utilize the formatting and preferences of the workspace if they are defined. For calling the `GlintLanguageServer` programmatically formatting and preferences can be passed but default to `{}` instead of being hardcoded at the call site.

Honor user formatting preferences in completions

---

packages/core/__tests__/cli/build-watch.test.ts
packages/core/__tests__/transform/debug.test.ts
packages/core/__tests__/transform/template-to-typescript.test.ts
packages/core/src/transform/template/template-to-typescript.ts

**Fix info from @dfreeman:**
Whether a file contains e.g. a `@glint-nocheck` directive doesn't impact what TypeScript itself sees in that module, only whether we emit errors from it or not. This means that in incremental builds, removing that directive won't produce a visible change from TypeScript's perspective, so we won't emit the now-revealed errors until the next time the `tsbuildinfo` cache is cleared.
This PR just has us emit a comment anywhere we see a `@glint` directive so that the contents of the transformed file will change if a directive comes or goes and TS will reconsider it for typechecking.
**Original writeup of the bug from @hmajoros:**
I believe I have found a bug in `glint --build --watch`, and generally, the same thing happens when running `glint --build` twice in a …

Ensure adding/removing directives busts any cached typecheck results

---

packages/core/__tests__/language-server/custom-extensions.test.ts
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/src/language-server/glint-language-server.ts
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/__tests__/smoketest-js-glimmerx.test.ts
packages/vscode/__tests__/smoketest-template-imports.test.ts

Now that we're correctly tracking diagnostic `code` in its own field, also embedding it in `source` is redundant and can result in the editor showing a diagnostic's code twice, e.g. `glint:ts(2345)(2345)`.
This change simplifies the source to just `glint` (dropping the `ts:` part, since we don't invent our own error codes apart from TypeScript's), allowing the editor to construct the tag as e.g. `glint(2345)` itself.

Don't duplicate diagnostic code information

---

packages/vscode/README.md
packages/vscode/src/extension.ts

Partially addresses #524, at least making it more explicit what's required. I'll also promote the extension from prerelease to stable when we do our next release so that folks no longer need to opt in to a beta version to have access to this piece of config.

Explicitly note the `Library Path` extension setting

---

packages/core/src/index.ts
packages/core/src/language-server/glint-language-server.ts

This PR updates `@glint/core` to expose a few more pieces of the language server implementation that should make it easier for Glint to be used programmatically (e.g. in https://github.com/rehearsal-js/rehearsal-js).

Expose TS language service and original document contents in `ProjectAnalysis`

---

.github/workflows/ci.yml

https://github.com/GabrielBB/xvfb-action is no longer maintained and uses a deprecated Node 12 action runner. The README there recommends using https://github.com/coactions/setup-xvfb instead, which has the same interface.

Switch to a maintained XVFB action in CI

---

packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/each-in.test.ts

Allow `each-in` to accept `key` as a named arg

---

packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/src/transform/diagnostics/augmentation.ts
packages/core/src/transform/template/template-to-typescript.ts
packages/environment-ember-loose/-private/dsl/index.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/component.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/helper.test.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/modifier.test.ts
packages/template/-private/keywords/-bind-invokable.d.ts
packages/template/__tests__/keywords/component.test.ts

The 1.0.0-beta.5 release of Glint introduced support for `{{helper}}` and `{{modifier}}` by way of a new `bind-invokable` abstraction based on the existing `{{component}}` implementation. As folks have kicked the tires on that refactor, a few bugs and inconsistencies have come to light:
- #559: the type signature allowed for multiple arguments, but due to some strange interactions in TypeScript's context-sensitive inference, it would frequently infer a version of the signature that only accepted one positional arg. We fix this by wrapping the `resolveForBind` call in an IIFE, which acts as an opaque barrier to context propagation for inference.
- #556: we weren't constraining the results of `bind-invokable` calls with `emitContent` as we should have when they appeared in a top-level …

Bugfixes for the beta.5 `bind-invokable` refactor

---

README.md
docs/contents.md
docs/diagnosing-common-error-messages.md
docs/directives.md
docs/ember/authoring-addons.md
docs/ember/installation.md
docs/glint-types.md
docs/known-limitations.md
docs/migrating.md
docs/overview.md

This PR contains a potpourri of small updates to the documentation site in preparation for 1.0:
- Restructuring the Contents sidebar to better account for some of the new top-level pages we've added
- Adding one last 0.9 -> 1.0 migration note around the type of `{{component 'foo'}}`
- Clarifying a few sections and adding some tips in response to some long-standing open question issues
- Removing the "we're pre-1.0 and unstable" warnings from various pages (🎉)
Obviously we can continue to iterate and expand after the stable release, but I believe this covers the last odds and ends that I knew of wanting to get straightened up before then.

1.0 Docs Updates

---

docs/ember/installation.md
docs/migrating.md
packages/environment-ember-loose/-private/dsl/index.d.ts
packages/environment-ember-loose/-private/dsl/without-function-resolution.d.ts
packages/environment-ember-loose/-private/environment/index.ts
packages/environment-ember-loose/__tests__/environment.test.ts
packages/environment-ember-loose/__tests__/type-tests/helper.test.ts
packages/environment-ember-loose/package.json

This was meant to land as part of 1.0 but got lost in a stash.
Maintaining two versions of the `ember-loose` types—one that supports functions-as-helpers and one that doesn't—is a maintenance burden we don't want to carry moving forward, particularly as an increasing number of consumers have native support, and nearly every consumer of Glint is on a version that supports the polyfill.

[Bugfix] Drop `allowPlainFunctionInvocation` flag

---

docs/getting-started.md

Fixes two broken links on "Getting Started" page.
- Removes link to docs page for `glint-language-server` that was removed in
https://github.com/typed-ember/glint/pull/416
- Fixes broken link to "Configuration"
There are a few other broken links throughout the docs but I don't understand how/why they're broken and they seem to magically sometimes not be broken in different preview versions.
For example, in the current live version of the ["Getting Started" page](https://typed-ember.gitbook.io/glint/getting-started) the link to "Ember.js Installation" does not work. The path looks correct to me and the link works properly on GitHub when previewing the markdown files.
If you view the preview "revision" linked by GitBook in the checks for this PR this link is magically fixed. I'm not sure if …

Fix broken links on "Getting Started" page

---

packages/core/__tests__/language-server/completions.test.ts
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/glint-language-server.ts

We fixed this for many cases in #442, but had an outstanding issue with embedded templates.
The root of the problem was essentially that I didn't want to plumb a `MappingTree` through a few layers of function indirection, and so we were answering the "is this completion being requested within a template?" question in two passes. Unfortunately, in cases with template a syntax error where the template was _in the same file as the backing class_, the second pass lookup of the mapping tree would fail, because the transformed offset would fall directly on the border between the template and the real JS/TS code.
This change fixes my original sin and plumbs through the relevant `MappingTree` as part of the transformed offset lookup process.
Fixes #566

Don't pollute completions with globals in templates with syntax errors

---

docs/ember/installation.md

Just what it says on the tin. The `ember-template-imports` bit was getting lost inside a Gitbook block for the code sample. 😭

Fix and extend ember-template-imports notes in installation.md

---

README.md

Just a drive-by - noticed these were broken.

Fix environment installation links in README.md

---

packages/environment-ember-loose/-private/intrinsics/link-to.d.ts

The `replace` argument was missing from the Glint types.
https://github.com/emberjs/ember.js/blob/v4.12.0/packages/@ember/-internals/glimmer/lib/components/link-to.ts#L468

Add missing argument to LinkTo component type

---

packages/core/src/index.ts

Expose loadConfig for consumers
> Since we already provide access to the GlintConfig instance to consumers who run analyzeProject, it seems reasonable to offer a way to load that config without forcing a full project analysis.
Closes https://github.com/typed-ember/glint/issues/579

Expose loadConfig

---

docs/getting-started.md
packages/vscode/README.md

As discussed here: https://discord.com/channels/480462759797063690/1135613767493881906/1135616206884323439
Also fixes the `<details>` section for the screenshot which requires a newline to render properly.

docs: document disabling VS Code TS plugin

---

packages/core/__tests__/cli/custom-extensions.test.ts
packages/core/__tests__/language-server/custom-extensions.test.ts
packages/core/src/cli/perform-build-watch.ts
packages/core/src/cli/perform-build.ts
packages/core/src/cli/perform-check.ts
packages/core/src/cli/perform-watch.ts
packages/core/src/cli/utils/transform-manager-pool.ts
packages/core/src/common/transform-manager.ts
packages/core/src/language-server/glint-language-server.ts
test-packages/ts-ember-app/types/global.d.ts
test-packages/ts-ember-preview-types/types/global.d.ts

This is an alternative approach to the one taken in #620, and fixes #618.
#620 attempts to support import paths with an explicit `.gts` extension by rewriting those imports during transformation, but module resolution really shouldn't be a concern of the transform layer. For example:
- It's important that we fix #618 in a way that works correctly even in files that we aren't transforming at all (consider that vanilla `.ts` files might import from `.gts` files)
- Glint is already required to intercept TypeScript's view of the project files in ways that the transform layer can't impact (consider that we already support imports of `.gts` files _without_ the extension)
TS has a hard-coded internal set of the extensions it considers to "be" TypeScript, and we work around this fact by …

Support custom extensions with `allowImportingTsExtensions`

---

docs/ember/installation.md

Tell the user which key they should add to tsconfig.json. The previous docs text stated that you "should configure it in `tsconfig.json` under `glint.environment`", but it did not say what key should be added.

Call out `ember-template-imports` config more clearly

---

packages/core/package.json
packages/core/src/language-server/util/index.ts
packages/vscode/package.json
yarn.lock

On projects using 1.2.0 of Glint, they'll run in to this:
```
file:///home/nvp/Development/NullVoxPopuli/polaris-starter-2/node_modules/.pnpm/@glint+core@1.2.0_typescript@5.2.2/node_modules/@glint/core/lib/language-server/util/index.js:3
import VSCodeURI from 'vscode-uri';
^^^^^^^^^
SyntaxError: The requested module 'vscode-uri' does not provide an export named 'default'
at ModuleJob._instantiate (node:internal/modules/esm/module_job:124:21)
at async ModuleJob.run (node:internal/modules/esm/module_job:190:5)
```
Which makes sense since `@glint/core` didn't declare a dep on `vscode-uri`.
Locally, when testing, I was using the 1.2.0 version of the language server, / vscode extension, so I don't know if that'll need to be published :shrug:

Update `vscode-uri` and match their docs

---

packages/core/README.md
packages/core/__tests__/cli/watch.test.ts
packages/core/src/cli/index.ts
packages/core/src/cli/options.ts
test-packages/test-utils/src/project.ts

Normally, output is cleared every time a change/re-check happens.
Correspondes to the tsc flag of the same name.

Add --preserveWatchOutput flag to avoid clearing console output in watch mode

---

docs/contents.md
docs/ember/installation.md
docs/ember/template-imports.md
docs/ember/template-only-components.md

Opening this PR as a result of the conversation [here](https://github.com/typed-ember/glint/discussions/641#discussioncomment-7496774).
This PR adds a `Template Imports` page to the docs to capture some details about how Glint can be used together with `ember-template-imports`

docs: Add "Template Imports" page

---

package.json
yarn.lock

Currently in CI in the floating-dependencies job we're running into conflicts between our own `@types/node` v18 and the various `*` constraints that come in transitively via DT packages. For our purposes it should be fine to just lock to a single version.

Lock @types/node to avoid issues in floating-dependencies CI

---

packages/core/__tests__/language-server/organize-imports.test.ts

I noticed on https://github.com/typed-ember/glint/pull/655, there were unrelated errors due to
- file not having correct syntax
- unrelated type error (missing arg)
This change fixes both issues
<details><summary>Nightly failures present on `main`</summary>
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
FAIL  __tests__/cli/custom-extensions.test.ts > CLI: custom extensions > external file changes > adding a missing module
Error: Timed out waiting to see "Found 0 errors.". Instead saw: ""
❯ Timeout.<anonymous> ../../test-packages/test-utils/src/project.ts:229:10
227|         detach();
228|         reject(
229|           new …
```

Fix organize-imports tests

---

.vscode/launch.json

Extracted from: https://github.com/typed-ember/glint/pull/655
This change allowed me to place breakpoints in the TS/source, and have those breakpoints hit while the "Debug Extension" task is ran.
<details><summary>Nightly failures present on `main`</summary>
```
⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯ Failed Tests 2 ⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯⎯
FAIL  __tests__/cli/custom-extensions.test.ts > CLI: custom extensions > external file changes > adding a missing module
Error: Timed out waiting to see "Found 0 errors.". Instead saw: ""
❯ Timeout.<anonymous> ../../test-packages/test-utils/src/project.ts:229:10
227|         detach();
228|         reject(
229| …
```

Fix debugging of TS Source so that breakpoints work when debugging the extension

---

packages/environment-ember-template-imports/package.json

While 
https://github.com/typed-ember/glint/pull/655
is being worked on, we need an interim solution for Glint.
Today, (for apps, addons, and v2 addons) it's broken out of the box for gts, because when folks install ember-template-imports, they get v4, which removed all the APIs Glint was using.
By moving ember-template-imports in Glint to be a dependency, Glint keeps those APIs, and is no longer broken-by-default.
This should be a patch-release, imo.

Move ember-template-imports to dependencies instead of peerDependencies

---

package.json
packages/core/package.json
test-packages/js-glimmerx-app/package.json
test-packages/ts-glimmerx-app/package.json
yarn.lock

All PRs / etc will have failing floating deps tests, due to something like this: https://github.com/typed-ember/glint/actions/runs/7513622017/job/20455581720?pr=680 (in the first run of this PR).
This PR narrows the `@glimmer/*` versions to something that works for CJS, as newer `@glimmer/*` is ESM only.
I deleted the lockfile and re-ran yarn, since that was the failing scenario on PRs.
`yarn@v1` treats `^` on pre-1.0 versions the same as post-1.0, which is dangerous for `@glimmer/*`

Fix deps, (because re-rolling the lockfile breaks everything)

---

ARCHITECTURE.md

At some point the `glint-environment` key was moved into `exports`; this PR updates the architecture docs to reflect that.

Docs: Update ARCHITECTURE to reflect latest API

---

.vscode/launch.json
package.json
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/src/common/transform-manager.ts
packages/core/src/transform/diagnostics/create-transform-diagnostic.ts
packages/core/src/transform/diagnostics/index.ts
packages/core/src/transform/template/rewrite-module.ts
packages/core/src/transform/template/transformed-module.ts
packages/environment-ember-template-imports/-private/environment/preprocess.ts
packages/environment-ember-template-imports/globals/index.d.ts
packages/environment-ember-template-imports/package.json
tsconfig.compileroptions.json
tsconfig.json
yarn.lock

**`ember-template-imports @ v4` removed all the APIs that glint was relying on for working with `<template>`-tags**
Resolves: https://github.com/typed-ember/glint/issues/609
Resolves: https://github.com/typed-ember/glint/issues/706
Resolves: https://github.com/typed-ember/glint/issues/694
~~Blocked by: https://github.com/embroider-build/content-tag/issues/19~~
~~Blocked by: https://github.com/embroider-build/content-tag/pull/31~~
Unblocks: https://github.com/NullVoxPopuli/polaris-starter/pull/11
Supersedes: https://github.com/typed-ember/glint/pull/615
Extractions:
- https://github.com/typed-ember/glint/pull/656
- https://github.com/typed-ember/glint/pull/657
Allows:
- folks to `<pm> add ember-template-imports` in their apps and not have to downgrade to v3 if they want to use Glint
- …

Use `content-tag` instead of `ember-template-imports`

---

packages/core/__tests__/transform/rewrite.test.ts
packages/core/src/transform/template/inlining/index.ts

support 
```gjs
class A extends X(<template></template>) {
}
```
currently the template part tries to have `A` as backing value

check if template is in heritage clause

---

docs/ember/template-imports.md
packages/type-test/README.md

Glimmer JS/TS syntax highlighting support was added to GitHub a couple of months ago. This PR uses that lang for codefences where `<template>` tag is being used.

docs: use gjs as codefence lang

---

.github/workflows/publish-unstable.yml
test-packages/unstable-release/.eslintrc.cjs
test-packages/unstable-release/README.md
test-packages/unstable-release/package.json
test-packages/unstable-release/publish.js
test-packages/unstable-release/version.js
test-packages/unstable-release/workspaces.js
yarn.lock

We aren't ready for `main` to go _stable_, but we want to enable folks trying out Volar.
This PR will release all the public packages to npm with the `unstable` tag and a git sha (short abbr) attached to the end of the version number -- like how embroider does it.
All of this code was copied from the embroider repo.

Setup unstable releases

---

packages/core/__tests__/cli/build-watch.test.ts
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/cli/custom-extensions.test.ts
packages/core/__tests__/cli/declaration.test.ts
packages/core/__tests__/cli/incremental.test.ts
packages/core/__tests__/cli/watch.test.ts
packages/core/__tests__/language-server/completions.test.ts
packages/core/__tests__/language-server/custom-extensions.test.ts
packages/core/__tests__/language-server/definitions.test.ts
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/__tests__/language-server/hover.test.ts
packages/core/__tests__/language-server/references.test.ts
packages/core/__tests__/language-server/symbol-search.test.ts
packages/core/src/cli/run-volar-tsc.ts
packages/environment-ember-loose/vitest.config.ts
packages/scripts/__tests__/auto-nocheck.test.ts
test-packages/test-utils/src/project.ts

This fixes or skips a number of test failures. At this point the only things failing are some of the type-tests, but don't have an immediate solution for those at this time. Probably make sense to merge this now.

Most of the way to green tests

---

test-packages/test-utils/src/project.ts

This fixes all remaining Windows test failures due to incorrect inline snapshot normalization.

Fix Windows snapshots

---

packages/core/src/cli/index.ts
packages/core/src/language-server/messages.cts
packages/core/src/transform/template/rewrite-module.ts
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/__tests__/smoketest-template-imports.test.ts
packages/vscode/package.json
packages/vscode/src/extension.ts

The getIR command was a helpful debugging command for replacing your open .gts / .hbs file with the type-checkable TS representation. With Volar, you just use the Volar Labs extension on an open file to show you the IR along with a ton of other helpful debugging/diagnostic tooling.

rm glint/getIR command

---

packages/core/__tests__/cli/build.test.ts
test-packages/test-utils/src/composite-project.ts
test-packages/test-utils/src/project.ts

Per [discussions](https://discord.com/channels/480462759797063690/717767358743183412/1257373912610766970) in Discord, I'm pushing Glint v2's cli tools to behave as closely as possible to vue-tsc, which itself behaves much more closely to vanilla `tsc`. This means breaking changes for people using `glint` for type-checking as a CLI task, but here are a few reasons this is desirable / forgivable:
1. The closer we are to Vue's tooling in general, the more we can tap into their larger community, e.g. there might be a confusion about glint that can be well explained by a closed issue in `vue-tsc`, rather than having this obscured by glint's behind-the-scenes flag-switching before shelling out to vanilla tsc.
2. Perhaps glint v2 can remove the `glint` binary and introduce a new one called …

Fix `glint` cli build tests, parity with `vue-tsc`

---

packages/core/__tests__/cli/build-watch.test.ts
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/cli/custom-extensions.test.ts
packages/core/__tests__/cli/watch.test.ts
test-packages/test-utils/src/project.ts

We're changing some of the behaviors around the glint CLI tools, and I wanted to make it more clear what particular operation was being triggered by which test method we were invoking on the test `Project` class. This should hopefully make it more clear.

Tests: Use clearer project testing commands

---

packages/core/__tests__/transform/rewrite.test.ts
packages/core/src/transform/template/inlining/index.ts

check if template is in heritage clause 

---

packages/core/__tests__/cli/check.test.ts
packages/core/__tests__/language-server/completions.test.ts
packages/core/__tests__/language-server/diagnostic-augmentation.test.ts
packages/core/src/cli/run-volar-tsc.ts
packages/core/src/config/config.ts
packages/core/src/transform/diagnostics/augmentation.ts
packages/core/src/transform/template/glimmer-ast-mapping-tree.ts
packages/core/src/transform/template/inlining/companion-file.ts
packages/core/src/transform/template/inlining/tagged-strings.ts
packages/core/src/transform/template/map-template-contents.ts
packages/core/src/transform/template/rewrite-module.ts
packages/core/src/transform/template/template-to-typescript.ts
packages/core/src/transform/template/transformed-module.ts
packages/core/src/volar/ember-language-plugin.ts
packages/core/src/volar/gts-language-plugin.ts
packages/core/src/volar/gts-virtual-code.ts
packages/core/src/volar/handlebars-virtual-code.ts
packages/core/src/volar/language-server.ts
packages/core/src/volar/loose-mode-backing-component-class-virtual-code.ts

Starts in on support for ember-loose mode, the classic Ember component authoring format when you provide (optional) backing .ts/.js class with a separate .hbs template file.
TL;DR, we can't follow support loose mode until we finish migrating to TS Plugin. Next steps are to find out how much of a lift that'll be.
- Volar only recently added support for two-file templating system (initially added for Angular-Webstorm; Angular has .ts files with .html template files)
- Volar's support only applies to TS Plugins, and does not currently offer support for two files in the (quickly-becoming-legacy) Language Server APIs
- This means Glint will need to convert to using TS Plugin before we can support this
- Alternatively Johnson from Volar might possibly be convinced to add support to the LS, but …

Primitives for supporting ember-loose mode (.ts + .hbs)

---

packages/environment-ember-loose/package.json

Apparently, @glimmer/component v2 is not allowed by current peerDependencies.
Same as #776, but targets `main` Volar.js based branch.

Widen peerDependencies to allow @glimmer/component v2

---

packages/core/package.json

Fix #778 - add missing dependency to @glint/core

---

packages/core/__tests__/config/load-config.test.ts
packages/core/src/config/loader.ts

Resolve glint configuration when your tsconfig.json extends from a package, ex
path: tsconfig.json
```json
{
"extends": "@package1"
}
```
path: node_modules/@package1/tsconfig.json
```json
{
"glint": {
"environment": ["ember-loose", "ember-template-imports"]
}
}
```

Typed ember/resolve config from extends package

---

packages/core/__tests__/config/load-config.test.ts
packages/core/src/config/loader.ts

Resolve glint configuration when your tsconfig.json extends from a package, ex
path: tsconfig.json
```json
{
"extends": "@package1"
}
```
path: node_modules/@package1/tsconfig.json
```json
{
"glint": {
"environment": ["ember-loose", "ember-template-imports"]
}
}
```
**Note**: I'm uncertain if this is the correct branch to merge with. If it isn't, please let me know.

Resolve config from extends package

---

packages/core/__tests__/language-server/diagnostics.test.ts
packages/vscode/__fixtures__/custom-app/src/index.custom
packages/vscode/__tests__/smoketest-ember.test.ts
packages/vscode/__tests__/smoketest-template-imports.test.ts

Soon we'll be writing acceptance tests to test out the ts-plugin mode (because Volar doesn't yet have testing facilities for ts-plugin and figuring out how to get [typescript-server-harness](https://github.com/microsoft/typescript-server-harness) working is too much of a lift). This PR reinstates previously pended acceptance tests for classic LS mode with the intent that a follow up PR will introduce acceptance tests that exercise the TS Plugin.

Reinstate acceptance tests (gts)

---

docs/ember/component-signatures.md

Update verbiage and add code example to make it clear how to handle scenarios where a component has no arguments or no block invocation

Clarify typing for no arguments/blocks

---

packages/vscode/__fixtures__/template-imports-app-ts-plugin/package.json
packages/vscode/__fixtures__/template-imports-app-ts-plugin/src/Greeting.gts
packages/vscode/__fixtures__/template-imports-app-ts-plugin/src/index.gts
packages/vscode/__fixtures__/template-imports-app-ts-plugin/tsconfig.json
packages/vscode/__tests__/helpers/async.ts
packages/vscode/__tests__/language-server-tests/smoketest-ember.test.ts
packages/vscode/__tests__/language-server-tests/smoketest-template-imports.test.ts
packages/vscode/__tests__/support/launch-from-cli.mts
packages/vscode/__tests__/support/vscode-runner-language-server.ts
packages/vscode/__tests__/support/vscode-runner-ts-plugin.ts
packages/vscode/__tests__/support/vscode-runner.ts
packages/vscode/__tests__/ts-plugin-tests/smoketest-template-imports-ts-plugin.test.ts
packages/vscode/package.json

Our only mechanism for testing TS-Plugin-based diagnostics is to use acceptance tests. This PR introduces the necessary changes to get acceptance tests (mocha tests running within a VSCode window) running in TS Plugin mode working.
There are a number of issues with TS Plugin mode right now so there are a few hacks to get the (currently) singular acceptance test passing, but these hacks will be removed over time.

Single acceptance test for ts plugin mode

---

.prettierignore
packages/vscode/.gitignore
packages/vscode/__tests__/support/launch-from-cli.mts
packages/vscode/package.json
packages/vscode/src/compatibility.ts
packages/vscode/src/config.ts
packages/vscode/src/extension.ts
packages/vscode/src/hybrid-mode.ts
packages/vscode/src/language-client.ts
packages/vscode/tsconfig.json
yarn.lock

The Vue extension which runs atop Volar still has a number of tricks (hacks?) to get typed Vue in TS Plugin mode (aka hybrid mode) working properly. It'll be easier to follow along with these hacks if our extension has as similar a structure as possible.
To that end I've followed along with the Vue extension's [refactor](https://github.com/vuejs/language-tools/pull/4945) to use [reactive-vscode](https://github.com/KermanX/reactive-vscode). `reactive-vscode` uses Vue's composition API (similar to starbeam signals/computeds/etc) to provide a more user-friendly reactive layer over the more observer-centric VSCode extension API. It's a nice set of primitives on its on but more importantly this lets us follow Vue's extension logic/hackery more closely.

Re-write extension to use reactive-vscode, align with Vue extension

---

packages/core/__tests__/cli/build-watch.test.ts
packages/core/__tests__/cli/build.test.ts
packages/core/__tests__/cli/check.test.ts
packages/core/__tests__/language-server/diagnostics.test.ts
packages/core/__tests__/language-server/hover.test.ts
packages/core/__tests__/language-server/references.test.ts
packages/core/__tests__/transform/template-to-typescript.test.ts
packages/core/src/transform/template/code-features.ts
packages/core/src/transform/template/glimmer-ast-mapping-tree.ts
packages/core/src/transform/template/inlining/companion-file.ts
packages/core/src/transform/template/inlining/tagged-strings.ts
packages/core/src/transform/template/map-template-contents.ts
packages/core/src/transform/template/template-to-typescript.ts
packages/core/src/transform/template/transformed-module.ts
packages/core/src/volar/language-server.ts
packages/core/src/volar/typescript-language-service-plugin.ts
test-packages/test-utils/src/project.ts

Support for `@glint-expect-error` was previously provided by monkeypatching the `typescript-semantic` Language Service plugin provided by Volar, but unfortunately:
1. This approach isn't used by TS Plugin mode
2. This approach isn't used by `runTsc` which our glint type-checking binary uses.
The solution is to move more of the expect-error (and other directive) logic into our mapping code so that when we call `toVolarMappings`, we can make use of the `shouldReport` callback to keep track of diagnostics raised within the `glint-expect-error` directive's area of effect. It is complicated and possibly brittle but at least it's in line with Vue, and any upstream breaking changes should be much easier to follow.
TODO
Closes #796
I might be actually impossible to restore exact semantics from …

Reinstate glint-expect-error (and other directives) for tsc and TS Plugin using Vue's approach

---

packages/typescript-plugin/package.json
packages/typescript-plugin/src/typescript-server-plugin.ts
yarn.lock

Closes #792
[jiti](https://github.com/unjs/jiti)'s synchronous API is deprecated, but using it is far superior to the hacks required and corner cases introduced by trying to use Volar's async plugin API.
Thank you to @johnsoncodehk for the recommendation.

Use jiti for sync loading from TS Plugin

---

packages/environment-ember-loose/-private/intrinsics/each-in.d.ts
packages/environment-ember-loose/__tests__/type-tests/intrinsics/each-in.test.ts

This allows us to extract the generic arguments and use them as the types for the default block.
Resolves: #645

Explicitly accept an Iterable in `each-in`

---

packages/core/__tests__/transform/rewrite.test.ts
packages/environment-ember-template-imports/-private/environment/transform.ts
packages/environment-ember-template-imports/__tests__/transformation.test.ts

Support implicit default export of template tags with satisfies keyword

---

packages/core/__tests__/config/load-config.test.ts
packages/core/src/config/loader.ts

Since TS5, tsconfig.json `extends` supports being an array of config files to extend.
Resolved #672

Support extending multiple config files

---

packages/vscode/README.md

Update info about not disabling the `@builtin typescript` extension forV2

---

packages/core/src/volar/ember-language-plugin.ts

Implement the perf optimization described here: https://github.com/typed-ember/glint/pull/851#issuecomment-2754636712
TL;DR minimize the parsing of non-loose-mode component .ts files by assuming that loose mode component .ts files are only going to be present in a `components/` folder, which is probably true for 99% of cases.

Loose mode: only parse .ts in `components/` folder

---

packages/vscode/src/extension.ts
tsconfig.compileroptions.json

1. Restore value to esModuleInterop=false so that `fs.readFileSync = ...` monkeypatch continues to work (with esModuleInterop=true, `fs = require(...)` becomes `fs = _importStar(require(...)` and you end up getting a "setting read-only property" error)
2. Remove the try catch wrapping to surface these issues in our test suite (and in the wild as more people start trying out the alpha)
I don't know exactly which specific features this restores; it didn't fix the auto-complete issues I'm seeing but I believe some cases of "Go to Definition" with .gts files have been fixed.

Disable esModuleInterop to restore VSCode monkeypatching

---

.eslintrc
.gitignore
CONTRIBUTING.md
bin/link-build.mjs
bin/link-install.mjs
bin/packages.mjs
package.json
packages/environment-ember-loose/package.json
packages/environment-ember-template-imports/package.json
packages/type-test/package.json
pnpm-lock.yaml

This is the same process that glimmer-vm uses to link up with ember-source
Example:
```bash
turborepo-summary-analyzer on  trial-glint-main [+]
origin  git@github.com:NullVoxPopuli/turborepo-summary-analyzer.git
took 3s
❯ node ../../OpenSource/glint/bin/link-install.mjs
{ packageJsonPaths: [ 'package.json' ] }
Gathering packages from 🏠/Development/OpenSource/glint/
Linking @glint/core within <repo>
Linking @glint/environment-ember-loose within <repo>
Linking @glint/environment-ember-template-imports within <repo>
Linking @glint/template within <repo>
Linking @glint/tsserver-plugin within <repo>
```
Without my terminal sanitizer:

Setup external project linking / testing

---

packages/environment-ember-template-imports/-private/environment/transform.ts
packages/environment-ember-template-imports/__tests__/transformation.test.ts

Previously all template tags with satisfies was transformed into an export default statement.

Only transform expression satisfies templates

---

package.json
packages/core/src/transform/template/rewrite-module.ts
packages/vscode/.vscodeignore
packages/vscode/__fixtures__/ember-app-loose-and-gts/app/components/Other.gts
packages/vscode/__fixtures__/ember-app-loose-and-gts/app/components/colocated-folder/index.gts
packages/vscode/__fixtures__/ember-app-loose-and-gts/app/components/pod-layout/component.ts
packages/vscode/__fixtures__/ember-app-loose-and-gts/app/components/pod-layout/template.hbs
packages/vscode/package.json
packages/vscode/scripts/build.mjs
packages/vscode/src/generated-meta.ts
test-packages/package-test-core/__tests__/language-server/imports.test.ts
test-packages/package-test-core/__tests__/transform/rewrite.test.ts
test-packages/ts-template-imports-app/src/colocated/index.gts

Inject hidden imports to fix `.gts`/`.gjs` extensions

---

packages/environment-ember-template-imports/-private/environment/transform.ts
test-packages/package-test-core/__tests__/transform/rewrite.test.ts

Follow up to 
- https://github.com/typed-ember/glint/pull/825

Fix handling of `satisfies` on components.

---

bin/link-build.mjs
bin/link-install.mjs
package.json
pnpm-lock.yaml

Seems easier to use tars instead of actual links.
This technique should also be compatible with folks using volta, since volta doesn't allow using `pnpm add -g`
(I use proto, tho)

Use the tars directly, rather than links

---

packages/core/src/transform/template/template-to-typescript.ts
test-packages/package-test-core/__tests__/transform/template-to-typescript.test.ts

Resolves #864 
Seems like there is an edge case with `action` helper, unsure if we should treat it as a bug in Ember or add an edge case for it in the `treatGlobal` check.
Ref: https://github.com/typed-ember/glint/issues/864#issuecomment-2764530407

Prefer variables in scope over global variables

---

docs/ember/template-imports.md

Follow-up to https://github.com/typed-ember/glint/pull/821
The bug that prevented this from working in apps has been fixed: https://github.com/embroider-build/content-tag/pull/97

Remove `export default` from the Template-only components example

---

packages/core/src/transform/template/map-template-contents.ts
packages/core/src/volar/language-server.ts
packages/tsserver-plugin/src/typescript-server-plugin.ts

Closes #835
The solution here is to classify the spans/mappings for the generated TS representing code within `<template>` regions as `shouldHightlight=false`. This tells volar to NOT reverse-source-map the classification tokens generated by vanilla TS when parsing the generated TS representation of .gts files.
This has the desired effect of preserving the tokens for the outer TS regions of the .gts file while ignoring the tokens for the templates. It may be desirable at some point in the future to see see how the default classifications for the template portion can be "fixed", but I don't have a sense for how difficult this might be. I suspect the reason the default classifications looking "wrong" is due to some of the constructs used for getting the type-checking aspect of Glint working …

Disregard semantic classification tokens from `<template>` portions of .gts files

---

packages/core/src/transform/template/rewrite-module.ts
test-packages/package-test-core/__tests__/transform/rewrite.test.ts

The hacks we were using to trick TS into considering `.gts`/`.gjs` to be valid implicit extensions (when omitted from import module specifiers) were causing issues with Organize Imports, due to the fact that the hacky fake imports were detected as "unused" and hence removed by Organize Imports in a manner that caused havok when the changes were reverse-source-mapped by Volar.
After some tinkering I landed on a solution that uses `await import()` which doesn't seem to get touched by Organize Imports.
Closes #867

Fix organize imports

---

packages/environment-ember-template-imports/__tests__/transformation.test.ts
test-packages/package-test-core/__tests__/language-server/diagnostic-augmentation.test.ts
test-packages/package-test-core/__tests__/transform/rewrite.test.ts

Extracted from https://github.com/typed-ember/glint/pull/882
This PR also does some test organization around character testing.
Ensuring:
- https://github.com/typed-ember/glint/issues/879
- https://github.com/typed-ember/glint/issues/840
- https://github.com/typed-ember/glint/issues/841

Add character tests

---

bin/build-elements.mjs
packages/template/-private/dsl/elements.d.ts
test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts

fix missing generic attrs for svg

---

packages/core/src/transform/diagnostics/augmentation.ts
packages/tsserver-plugin/src/typescript-server-plugin.ts
test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts

Followup to #888; this PR reinstates the "unused @glint-expect-error directive" diagnostic that emits when no diagnostics are emitted within a `@glint-expect-error`'s area of effect.

Reinstate "unused @glint-expect-error directive"

---

.vscode/launch.json

The launch configurations were useful when "takeover mode" was still a possible configuration, but Glint 2 has committed to TS Plugin mode so there's no need for these launch configurations anymore.

Remove deprecated F5 launch configurations

---

package.json
packages/core/package.json
packages/environment-ember-loose/package.json
packages/environment-ember-template-imports/package.json
packages/tsserver-plugin/package.json
packages/type-test/package.json
packages/vscode/package.json
test-packages/test-utils/package.json
test-packages/ts-ember-app/package.json
test-packages/ts-ember-preview-types/package.json
test-packages/ts-plugin-test-app/package.json
test-packages/ts-template-imports-app/package.json

This allows us to use glint "@ main" in blueprints, which unblocks:
https://github.com/ember-cli/ember-addon-blueprint/pull/57

Setup alpha releases

---

.github/workflows/publish.yml
packages/core/README.md
packages/environment-ember-loose/README.md
packages/environment-ember-template-imports/README.md
packages/template/README.md
packages/tsserver-plugin/README.md
packages/type-test/README.md

We have a new release system (release-plan), and I forgot to configure it to handle our non-package-centric build

Fix build to prepare for re-releasing alphas

---

packages/core/src/transform/diagnostics/augmentation.ts
packages/core/src/transform/template/inlining/tagged-strings.ts
packages/core/src/transform/template/map-template-contents.ts
packages/core/src/transform/template/rewrite-module.ts
packages/core/src/transform/template/template-to-typescript.ts
packages/core/src/transform/template/transformed-module.ts
packages/tsserver-plugin/src/typescript-server-plugin.ts
packages/vscode/__fixtures__/ember-app-loose-and-gts/app/components/Greeting-expect-error.gts
test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts

Closes #898
Reconstruct our implementation of glint-expect-error/glint-ignore to live entirely within the VirtualCodes parsing/mapping system, which runs in all contexts including `tsc` CLI (i.e. the `glint` binary).

Reinstate directives in a way that works with tsc (glint binary)

---

packages/core/src/transform/template/template-to-typescript.ts
packages/core/src/transform/template/transformed-module.ts
pnpm-lock.yaml
test-packages/package-test-core/__tests__/language-server/diagnostics.test.ts
test-packages/ts-template-imports-app/package.json

More generally: allow transformed/generated code to map back to the same region of source.
Closes #921

Fix diagnostics for modifiers and other cases

---

packages/core/src/transform/template/transformed-module.ts

Closes #956
There wasn't really a good way to test this because the only diagnostic that would even show up to demonstrate bad reverse source mapping was fixed in #955. But this new logic addresses some afore-commented hackiness and I validated through Volar Labs that the underlying issue was fixed.

Fix occasional source mapping errors

---

packages/core/src/transform/diagnostics/augmentation.ts
packages/core/src/transform/template/template-to-typescript.ts
test-packages/package-test-core/__tests__/transform/rewrite.test.ts

Closes #920
This will be especially important for the v2 upgrade, as the Glint v2 VSCode extension requires that project dependencies also use v2 `@glint` packages. Without this PR, the import of glint types within the generated/transformed .ts code would quietly fail with no diagnostics surfacing in the .gts/.gjs file, and while Go-to-Def and other tooling might still work, a lot of the types would should up as `any`. With this PR they'll get a nicely formatted message about the dependency mismatch.

Surface v1/v2 dep mismatch errors

---

packages/core/package.json
packages/template/package.json
packages/tsserver-plugin/package.json
packages/type-test/package.json

A few more things to flesh out before we prep for release.
This reverts commit 046cfa6961fffb974fb45a2e721de1ebe082b3ea.

Revert "Remove release-plan alpha configuration for v2 prep (#975)"

---

docs/v2-upgrade.md

I've run [`ember-codemod-add-template-tags`](https://github.com/ijlee2/ember-codemod-add-template-tags) on several production apps and addons this week. I'd like to list it as an option for how to migrate from `*.hbs` files and `hbs` tags.

Listed ember-codemod-add-template-tags as a migration option

---

README.md

Removed 'Alpha' designation from Glint 2 section.

Update README to reflect Glint 2 status
